import { Milestone, DomainOverview } from '@/types/milestones';
import { LearningDomain } from '@/types/curriculum';

export const DOMAIN_OVERVIEWS: DomainOverview[] = [
  {
    domain: 'cognitive',
    description: 'Problem-solving, memory, attention, and logical thinking skills',
    icon: 'Brain',
    parentFriendlyName: 'Thinking & Problem Solving',
  },
  {
    domain: 'language',
    description: 'Speaking, listening, vocabulary, and communication abilities',
    icon: 'MessageCircle',
    parentFriendlyName: 'Language & Communication',
  },
  {
    domain: 'physical',
    description: 'Gross motor, fine motor, coordination, and physical health',
    icon: 'Activity',
    parentFriendlyName: 'Physical Development',
  },
  {
    domain: 'social-emotional',
    description: 'Relationships, self-regulation, empathy, and emotional awareness',
    icon: 'Heart',
    parentFriendlyName: 'Social & Emotional',
  },
  {
    domain: 'creative',
    description: 'Art, music, imaginative play, and creative expression',
    icon: 'Palette',
    parentFriendlyName: 'Creativity & Arts',
  },
  {
    domain: 'literacy',
    description: 'Pre-reading, early writing, phonics, and book awareness',
    icon: 'BookOpen',
    parentFriendlyName: 'Early Literacy',
  },
  {
    domain: 'math',
    description: 'Numbers, patterns, shapes, sorting, and early math concepts',
    icon: 'Calculator',
    parentFriendlyName: 'Math & Numbers',
  },
];

export const MILESTONES: Milestone[] = [
  // ==================== INFANT ====================
  // Cognitive
  {
    id: 'inf-cog-1',
    title: 'Tracks moving objects',
    description: 'Follows objects and people with their eyes as they move',
    domain: 'cognitive',
    ageGroup: 'infant',
    order: 1,
    examples: ['Watches a rattle move across vision', 'Follows caregiver around room'],
    parentTip: 'Move colorful toys slowly in front of your baby',
  },
  {
    id: 'inf-cog-2',
    title: 'Explores cause and effect',
    description: 'Discovers that actions cause reactions',
    domain: 'cognitive',
    ageGroup: 'infant',
    order: 2,
    examples: ['Shakes rattle to hear sound', 'Drops toy and looks for it'],
    parentTip: 'Provide toys that respond to touch or movement',
  },
  {
    id: 'inf-cog-3',
    title: 'Develops object permanence',
    description: 'Understands objects exist even when out of sight',
    domain: 'cognitive',
    ageGroup: 'infant',
    order: 3,
    examples: ['Looks for hidden toy', 'Anticipates peek-a-boo'],
    parentTip: 'Play peek-a-boo and hide-and-find games',
  },
  // Language
  {
    id: 'inf-lang-1',
    title: 'Responds to sounds and voices',
    description: 'Turns toward sounds and recognizes familiar voices',
    domain: 'language',
    ageGroup: 'infant',
    order: 1,
    examples: ['Turns head toward parent voice', 'Calms when hearing familiar songs'],
    parentTip: 'Talk, sing, and read to your baby throughout the day',
  },
  {
    id: 'inf-lang-2',
    title: 'Coos and babbles',
    description: 'Makes vowel sounds and early babbling',
    domain: 'language',
    ageGroup: 'infant',
    order: 2,
    examples: ['Says "ooh" and "aah"', 'Babbles "ba-ba" or "da-da"'],
    parentTip: 'Respond to your baby\'s sounds as if having a conversation',
  },
  {
    id: 'inf-lang-3',
    title: 'Understands simple words',
    description: 'Responds to their name and common words',
    domain: 'language',
    ageGroup: 'infant',
    order: 3,
    examples: ['Looks up when name is called', 'Responds to "no"'],
    parentTip: 'Use their name often and narrate daily activities',
  },
  // Physical
  {
    id: 'inf-phys-1',
    title: 'Develops head control',
    description: 'Holds head steady and lifts during tummy time',
    domain: 'physical',
    ageGroup: 'infant',
    order: 1,
    examples: ['Holds head up while on tummy', 'Lifts head while being held'],
    parentTip: 'Practice tummy time several times daily',
  },
  {
    id: 'inf-phys-2',
    title: 'Reaches and grasps',
    description: 'Reaches for objects and holds them in hands',
    domain: 'physical',
    ageGroup: 'infant',
    order: 2,
    examples: ['Reaches for hanging toys', 'Grasps finger or rattle'],
    parentTip: 'Offer safe objects within reach to encourage grasping',
  },
  {
    id: 'inf-phys-3',
    title: 'Rolls and sits',
    description: 'Learns to roll over and sit with support',
    domain: 'physical',
    ageGroup: 'infant',
    order: 3,
    examples: ['Rolls from tummy to back', 'Sits with support'],
    parentTip: 'Create safe spaces for floor play and movement',
  },
  // Social-Emotional
  {
    id: 'inf-se-1',
    title: 'Forms secure attachments',
    description: 'Bonds with caregivers and shows preference',
    domain: 'social-emotional',
    ageGroup: 'infant',
    order: 1,
    examples: ['Smiles at familiar faces', 'Calms when held by caregiver'],
    parentTip: 'Respond consistently to your baby\'s needs',
  },
  {
    id: 'inf-se-2',
    title: 'Expresses emotions',
    description: 'Shows range of emotions through facial expressions and sounds',
    domain: 'social-emotional',
    ageGroup: 'infant',
    order: 2,
    examples: ['Smiles socially', 'Cries to communicate needs'],
    parentTip: 'Name your baby\'s emotions as you respond to them',
  },
  {
    id: 'inf-se-3',
    title: 'Engages in social play',
    description: 'Enjoys interactive play with caregivers',
    domain: 'social-emotional',
    ageGroup: 'infant',
    order: 3,
    examples: ['Laughs during peek-a-boo', 'Reaches for caregiver to play'],
    parentTip: 'Make eye contact and play simple interactive games',
  },
  // Creative
  {
    id: 'inf-cre-1',
    title: 'Explores sensory materials',
    description: 'Investigates textures, sounds, and visual stimuli',
    domain: 'creative',
    ageGroup: 'infant',
    order: 1,
    examples: ['Touches different textures', 'Watches colorful mobiles'],
    parentTip: 'Provide safe sensory experiences with varied textures',
  },
  {
    id: 'inf-cre-2',
    title: 'Responds to music',
    description: 'Reacts to rhythm and melody',
    domain: 'creative',
    ageGroup: 'infant',
    order: 2,
    examples: ['Moves body to music', 'Calms to lullabies'],
    parentTip: 'Sing songs and play different types of music',
  },

  // ==================== TODDLER ====================
  // Cognitive
  {
    id: 'tod-cog-1',
    title: 'Sorts objects by attribute',
    description: 'Groups items by color, shape, or size',
    domain: 'cognitive',
    ageGroup: 'toddler',
    order: 1,
    examples: ['Puts all red blocks together', 'Sorts big and small items'],
    parentTip: 'Ask your child to help sort laundry by color',
  },
  {
    id: 'tod-cog-2',
    title: 'Completes simple puzzles',
    description: 'Fits shapes into corresponding holes',
    domain: 'cognitive',
    ageGroup: 'toddler',
    order: 2,
    examples: ['Completes 3-4 piece puzzle', 'Uses shape sorter'],
    parentTip: 'Start with simple puzzles and gradually increase difficulty',
  },
  {
    id: 'tod-cog-3',
    title: 'Understands routines',
    description: 'Anticipates daily sequences and transitions',
    domain: 'cognitive',
    ageGroup: 'toddler',
    order: 3,
    examples: ['Knows snack comes after play', 'Gets shoes before going outside'],
    parentTip: 'Maintain consistent routines and talk about what comes next',
  },
  {
    id: 'tod-cog-4',
    title: 'Engages in pretend play',
    description: 'Uses imagination to act out scenarios',
    domain: 'cognitive',
    ageGroup: 'toddler',
    order: 4,
    examples: ['Feeds baby doll', 'Pretends to talk on phone'],
    parentTip: 'Join in pretend play and follow your child\'s lead',
  },
  // Language
  {
    id: 'tod-lang-1',
    title: 'Uses two-word phrases',
    description: 'Combines words to express ideas',
    domain: 'language',
    ageGroup: 'toddler',
    order: 1,
    examples: ['Says "more milk"', 'Says "daddy go"'],
    parentTip: 'Expand on your child\'s phrases: "Yes, daddy is going to work"',
  },
  {
    id: 'tod-lang-2',
    title: 'Follows simple directions',
    description: 'Understands and responds to one-step instructions',
    domain: 'language',
    ageGroup: 'toddler',
    order: 2,
    examples: ['Gets shoes when asked', 'Puts toy in box'],
    parentTip: 'Give one clear direction at a time',
  },
  {
    id: 'tod-lang-3',
    title: 'Names familiar objects',
    description: 'Identifies and labels common items',
    domain: 'language',
    ageGroup: 'toddler',
    order: 3,
    examples: ['Points to and names dog', 'Labels body parts'],
    parentTip: 'Point out and name things during daily activities',
  },
  {
    id: 'tod-lang-4',
    title: 'Enjoys books and stories',
    description: 'Shows interest in being read to',
    domain: 'language',
    ageGroup: 'toddler',
    order: 4,
    examples: ['Brings books to caregiver', 'Points at pictures'],
    parentTip: 'Read together daily and let your child turn pages',
  },
  // Physical
  {
    id: 'tod-phys-1',
    title: 'Walks and runs',
    description: 'Moves independently with increasing coordination',
    domain: 'physical',
    ageGroup: 'toddler',
    order: 1,
    examples: ['Walks without falling', 'Runs with control'],
    parentTip: 'Provide safe spaces for active movement',
  },
  {
    id: 'tod-phys-2',
    title: 'Climbs safely',
    description: 'Navigates climbing structures with supervision',
    domain: 'physical',
    ageGroup: 'toddler',
    order: 2,
    examples: ['Climbs onto furniture', 'Goes up stairs with help'],
    parentTip: 'Supervise climbing and teach safe techniques',
  },
  {
    id: 'tod-phys-3',
    title: 'Uses utensils',
    description: 'Feeds self with spoon and fork',
    domain: 'physical',
    ageGroup: 'toddler',
    order: 3,
    examples: ['Scoops food with spoon', 'Drinks from open cup'],
    parentTip: 'Allow messy practice - it builds coordination',
  },
  {
    id: 'tod-phys-4',
    title: 'Scribbles with crayons',
    description: 'Makes marks on paper with writing tools',
    domain: 'physical',
    ageGroup: 'toddler',
    order: 4,
    examples: ['Holds crayon and scribbles', 'Makes intentional marks'],
    parentTip: 'Offer large crayons and big paper for practice',
  },
  // Social-Emotional
  {
    id: 'tod-se-1',
    title: 'Shows independence',
    description: 'Wants to do things on their own',
    domain: 'social-emotional',
    ageGroup: 'toddler',
    order: 1,
    examples: ['Says "me do it"', 'Tries to dress self'],
    parentTip: 'Allow extra time for your child to try independently',
  },
  {
    id: 'tod-se-2',
    title: 'Plays alongside others',
    description: 'Engages in parallel play near peers',
    domain: 'social-emotional',
    ageGroup: 'toddler',
    order: 2,
    examples: ['Plays near other children', 'Watches and imitates peers'],
    parentTip: 'Arrange playdates to build social skills',
  },
  {
    id: 'tod-se-3',
    title: 'Expresses emotions with words',
    description: 'Begins to label feelings',
    domain: 'social-emotional',
    ageGroup: 'toddler',
    order: 3,
    examples: ['Says "I mad"', 'Identifies happy and sad'],
    parentTip: 'Read books about feelings and name emotions throughout the day',
  },
  {
    id: 'tod-se-4',
    title: 'Seeks comfort',
    description: 'Goes to caregiver when upset or hurt',
    domain: 'social-emotional',
    ageGroup: 'toddler',
    order: 4,
    examples: ['Brings blanket for comfort', 'Asks for hugs'],
    parentTip: 'Always provide comfort when your child needs it',
  },
  // Creative
  {
    id: 'tod-cre-1',
    title: 'Explores art materials',
    description: 'Experiments with paint, playdough, and crayons',
    domain: 'creative',
    ageGroup: 'toddler',
    order: 1,
    examples: ['Finger paints', 'Squishes playdough'],
    parentTip: 'Focus on the process, not the product',
  },
  {
    id: 'tod-cre-2',
    title: 'Dances and moves to music',
    description: 'Moves body rhythmically to songs',
    domain: 'creative',
    ageGroup: 'toddler',
    order: 2,
    examples: ['Bounces to music', 'Does action songs'],
    parentTip: 'Have dance parties and sing action songs together',
  },
  {
    id: 'tod-cre-3',
    title: 'Engages in dramatic play',
    description: 'Acts out familiar scenarios with props',
    domain: 'creative',
    ageGroup: 'toddler',
    order: 3,
    examples: ['Plays house', 'Pretends to cook'],
    parentTip: 'Provide dress-up clothes and play kitchen items',
  },
  // Literacy
  {
    id: 'tod-lit-1',
    title: 'Holds books correctly',
    description: 'Understands how books work',
    domain: 'literacy',
    ageGroup: 'toddler',
    order: 1,
    examples: ['Holds book right-side up', 'Turns pages front to back'],
    parentTip: 'Model how to handle books gently',
  },
  {
    id: 'tod-lit-2',
    title: 'Points to pictures',
    description: 'Identifies images in books',
    domain: 'literacy',
    ageGroup: 'toddler',
    order: 2,
    examples: ['Points when asked "Where\'s the dog?"', 'Names pictures'],
    parentTip: 'Ask questions about pictures while reading',
  },
  // Math
  {
    id: 'tod-math-1',
    title: 'Understands "more"',
    description: 'Recognizes quantity concepts',
    domain: 'math',
    ageGroup: 'toddler',
    order: 1,
    examples: ['Asks for more crackers', 'Points to bigger pile'],
    parentTip: 'Use math words: more, less, bigger, smaller',
  },
  {
    id: 'tod-math-2',
    title: 'Counts with help',
    description: 'Begins rote counting with assistance',
    domain: 'math',
    ageGroup: 'toddler',
    order: 2,
    examples: ['Says numbers in sequence', 'Counts fingers with help'],
    parentTip: 'Count stairs, snacks, and toys throughout the day',
  },

  // ==================== PRESCHOOL ====================
  // Cognitive
  {
    id: 'pre-cog-1',
    title: 'Asks "why" questions',
    description: 'Shows curiosity about how things work',
    domain: 'cognitive',
    ageGroup: 'preschool',
    order: 1,
    examples: ['Asks why sky is blue', 'Wants to know how things work'],
    parentTip: 'Welcome questions and explore answers together',
  },
  {
    id: 'pre-cog-2',
    title: 'Solves simple problems',
    description: 'Thinks through challenges independently',
    domain: 'cognitive',
    ageGroup: 'preschool',
    order: 2,
    examples: ['Figures out how puzzle piece fits', 'Decides how to build tower'],
    parentTip: 'Resist solving problems for them - ask guiding questions instead',
  },
  {
    id: 'pre-cog-3',
    title: 'Remembers and retells',
    description: 'Recalls past events and stories',
    domain: 'cognitive',
    ageGroup: 'preschool',
    order: 3,
    examples: ['Tells about trip to park', 'Retells favorite story'],
    parentTip: 'Ask about their day and past experiences',
  },
  {
    id: 'pre-cog-4',
    title: 'Understands time concepts',
    description: 'Grasps yesterday, today, tomorrow',
    domain: 'cognitive',
    ageGroup: 'preschool',
    order: 4,
    examples: ['Knows morning vs. night', 'Understands "after lunch"'],
    parentTip: 'Use time words in daily conversation',
  },
  {
    id: 'pre-cog-5',
    title: 'Completes multi-step tasks',
    description: 'Follows sequences with 2-3 steps',
    domain: 'cognitive',
    ageGroup: 'preschool',
    order: 5,
    examples: ['Gets shoes, puts them on, then gets coat', 'Follows recipe steps'],
    parentTip: 'Give multi-step directions and celebrate success',
  },
  // Language
  {
    id: 'pre-lang-1',
    title: 'Speaks in full sentences',
    description: 'Uses 5-6 word sentences with correct grammar',
    domain: 'language',
    ageGroup: 'preschool',
    order: 1,
    examples: ['Says "I want to go outside"', 'Tells complete stories'],
    parentTip: 'Have back-and-forth conversations at meals',
  },
  {
    id: 'pre-lang-2',
    title: 'Asks and answers questions',
    description: 'Engages in question-and-answer exchanges',
    domain: 'language',
    ageGroup: 'preschool',
    order: 2,
    examples: ['Asks "What are we having for lunch?"', 'Answers who, what, where'],
    parentTip: 'Ask open-ended questions and wait for full answers',
  },
  {
    id: 'pre-lang-3',
    title: 'Uses descriptive language',
    description: 'Includes adjectives and details',
    domain: 'language',
    ageGroup: 'preschool',
    order: 3,
    examples: ['Says "big red truck"', 'Describes feelings in detail'],
    parentTip: 'Model descriptive language when talking',
  },
  {
    id: 'pre-lang-4',
    title: 'Follows complex directions',
    description: 'Understands multi-step instructions',
    domain: 'language',
    ageGroup: 'preschool',
    order: 4,
    examples: ['Follows "Put your shoes by the door and wash your hands"'],
    parentTip: 'Give directions with clear sequence words (first, then, last)',
  },
  // Physical
  {
    id: 'pre-phys-1',
    title: 'Runs, jumps, and hops',
    description: 'Demonstrates coordinated gross motor skills',
    domain: 'physical',
    ageGroup: 'preschool',
    order: 1,
    examples: ['Hops on one foot', 'Jumps over objects'],
    parentTip: 'Create obstacle courses and active play opportunities',
  },
  {
    id: 'pre-phys-2',
    title: 'Catches and throws',
    description: 'Plays ball games with improving accuracy',
    domain: 'physical',
    ageGroup: 'preschool',
    order: 2,
    examples: ['Catches bounced ball', 'Throws overhand'],
    parentTip: 'Start with larger, softer balls and work up',
  },
  {
    id: 'pre-phys-3',
    title: 'Uses scissors',
    description: 'Cuts along lines with child-safe scissors',
    domain: 'physical',
    ageGroup: 'preschool',
    order: 3,
    examples: ['Cuts straight lines', 'Cuts out simple shapes'],
    parentTip: 'Practice cutting playdough before paper',
  },
  {
    id: 'pre-phys-4',
    title: 'Draws recognizable shapes',
    description: 'Creates circles, lines, and basic forms',
    domain: 'physical',
    ageGroup: 'preschool',
    order: 4,
    examples: ['Draws person with head and body', 'Makes recognizable letters'],
    parentTip: 'Encourage drawing and don\'t correct - celebrate effort',
  },
  {
    id: 'pre-phys-5',
    title: 'Manages self-care',
    description: 'Handles basic hygiene and dressing',
    domain: 'physical',
    ageGroup: 'preschool',
    order: 5,
    examples: ['Washes and dries hands', 'Puts on coat independently'],
    parentTip: 'Build in extra time for independent self-care',
  },
  // Social-Emotional
  {
    id: 'pre-se-1',
    title: 'Plays cooperatively',
    description: 'Engages in interactive play with peers',
    domain: 'social-emotional',
    ageGroup: 'preschool',
    order: 1,
    examples: ['Takes turns in games', 'Collaborates on building projects'],
    parentTip: 'Praise specific cooperative behaviors you observe',
  },
  {
    id: 'pre-se-2',
    title: 'Manages emotions',
    description: 'Uses strategies to calm down',
    domain: 'social-emotional',
    ageGroup: 'preschool',
    order: 2,
    examples: ['Takes deep breaths when upset', 'Uses words instead of hitting'],
    parentTip: 'Teach and practice calming strategies when calm',
  },
  {
    id: 'pre-se-3',
    title: 'Shows empathy',
    description: 'Recognizes and responds to others\' feelings',
    domain: 'social-emotional',
    ageGroup: 'preschool',
    order: 3,
    examples: ['Comforts sad friend', 'Notices when someone is hurt'],
    parentTip: 'Point out others\' emotions and discuss how to help',
  },
  {
    id: 'pre-se-4',
    title: 'Follows classroom rules',
    description: 'Understands and respects group expectations',
    domain: 'social-emotional',
    ageGroup: 'preschool',
    order: 4,
    examples: ['Raises hand to speak', 'Cleans up after activities'],
    parentTip: 'Have clear, consistent rules at home too',
  },
  {
    id: 'pre-se-5',
    title: 'Expresses needs appropriately',
    description: 'Asks for help and communicates wants',
    domain: 'social-emotional',
    ageGroup: 'preschool',
    order: 5,
    examples: ['Says "I need help"', 'Uses words to ask for turn'],
    parentTip: 'Model and encourage using words for needs',
  },
  // Creative
  {
    id: 'pre-cre-1',
    title: 'Creates representational art',
    description: 'Draws and creates with intention',
    domain: 'creative',
    ageGroup: 'preschool',
    order: 1,
    examples: ['Draws family picture', 'Builds recognizable structures'],
    parentTip: 'Ask "Tell me about your picture" instead of guessing',
  },
  {
    id: 'pre-cre-2',
    title: 'Engages in elaborate pretend play',
    description: 'Creates complex imaginative scenarios',
    domain: 'creative',
    ageGroup: 'preschool',
    order: 2,
    examples: ['Acts out stories with friends', 'Creates pretend worlds'],
    parentTip: 'Provide open-ended materials for creative play',
  },
  {
    id: 'pre-cre-3',
    title: 'Sings songs and moves to music',
    description: 'Participates in music activities',
    domain: 'creative',
    ageGroup: 'preschool',
    order: 3,
    examples: ['Sings familiar songs', 'Moves creatively to music'],
    parentTip: 'Sing together during car rides and daily routines',
  },
  {
    id: 'pre-cre-4',
    title: 'Builds and constructs',
    description: 'Uses blocks and materials to create structures',
    domain: 'creative',
    ageGroup: 'preschool',
    order: 4,
    examples: ['Builds tall towers', 'Creates enclosures and bridges'],
    parentTip: 'Provide various building materials and time to explore',
  },
  // Literacy
  {
    id: 'pre-lit-1',
    title: 'Recognizes letters',
    description: 'Identifies letters by name',
    domain: 'literacy',
    ageGroup: 'preschool',
    order: 1,
    examples: ['Names letters in own name', 'Points out letters in environment'],
    parentTip: 'Point out letters on signs and in books',
  },
  {
    id: 'pre-lit-2',
    title: 'Understands print concepts',
    description: 'Knows how books and print work',
    domain: 'literacy',
    ageGroup: 'preschool',
    order: 2,
    examples: ['Knows we read left to right', 'Identifies front cover'],
    parentTip: 'Track words with your finger while reading',
  },
  {
    id: 'pre-lit-3',
    title: 'Hears rhymes and sounds',
    description: 'Develops phonological awareness',
    domain: 'literacy',
    ageGroup: 'preschool',
    order: 3,
    examples: ['Identifies rhyming words', 'Claps syllables in words'],
    parentTip: 'Read rhyming books and play word games',
  },
  {
    id: 'pre-lit-4',
    title: 'Writes own name',
    description: 'Writes recognizable letters in name',
    domain: 'literacy',
    ageGroup: 'preschool',
    order: 4,
    examples: ['Writes first name', 'Makes letter-like forms'],
    parentTip: 'Provide opportunities to practice writing daily',
  },
  {
    id: 'pre-lit-5',
    title: 'Retells familiar stories',
    description: 'Recalls story elements in sequence',
    domain: 'literacy',
    ageGroup: 'preschool',
    order: 5,
    examples: ['Tells what happened in story', 'Predicts what comes next'],
    parentTip: 'Ask questions before, during, and after reading',
  },
  // Math
  {
    id: 'pre-math-1',
    title: 'Counts to 20',
    description: 'Counts objects with one-to-one correspondence',
    domain: 'math',
    ageGroup: 'preschool',
    order: 1,
    examples: ['Counts snacks accurately', 'Counts objects up to 20'],
    parentTip: 'Count everything - stairs, toys, snacks',
  },
  {
    id: 'pre-math-2',
    title: 'Recognizes numbers',
    description: 'Identifies written numerals 0-10',
    domain: 'math',
    ageGroup: 'preschool',
    order: 2,
    examples: ['Names numbers on signs', 'Matches number to quantity'],
    parentTip: 'Point out numbers in daily life',
  },
  {
    id: 'pre-math-3',
    title: 'Identifies shapes',
    description: 'Names and describes basic shapes',
    domain: 'math',
    ageGroup: 'preschool',
    order: 3,
    examples: ['Identifies circle, square, triangle', 'Finds shapes in environment'],
    parentTip: 'Go on shape hunts around the house',
  },
  {
    id: 'pre-math-4',
    title: 'Compares quantities',
    description: 'Understands more, less, and equal',
    domain: 'math',
    ageGroup: 'preschool',
    order: 4,
    examples: ['Identifies who has more', 'Sorts by size'],
    parentTip: 'Compare groups of objects during play',
  },
  {
    id: 'pre-math-5',
    title: 'Creates patterns',
    description: 'Recognizes and extends simple patterns',
    domain: 'math',
    ageGroup: 'preschool',
    order: 5,
    examples: ['Continues AB pattern', 'Creates own patterns'],
    parentTip: 'Make patterns with snacks, toys, or movements',
  },

  // ==================== SCHOOL AGE ====================
  // Cognitive
  {
    id: 'sch-cog-1',
    title: 'Thinks logically',
    description: 'Uses reasoning to solve problems',
    domain: 'cognitive',
    ageGroup: 'school-age',
    order: 1,
    examples: ['Works through math problems', 'Explains thinking process'],
    parentTip: 'Ask "How did you figure that out?" to encourage reflection',
  },
  {
    id: 'sch-cog-2',
    title: 'Plans and organizes',
    description: 'Manages tasks and materials',
    domain: 'cognitive',
    ageGroup: 'school-age',
    order: 2,
    examples: ['Organizes homework', 'Plans steps for projects'],
    parentTip: 'Help create checklists and organizational systems',
  },
  {
    id: 'sch-cog-3',
    title: 'Focuses attention',
    description: 'Sustains concentration on tasks',
    domain: 'cognitive',
    ageGroup: 'school-age',
    order: 3,
    examples: ['Completes homework independently', 'Reads for extended periods'],
    parentTip: 'Create a quiet study space free from distractions',
  },
  {
    id: 'sch-cog-4',
    title: 'Thinks critically',
    description: 'Evaluates information and forms opinions',
    domain: 'cognitive',
    ageGroup: 'school-age',
    order: 4,
    examples: ['Questions what they read', 'Considers multiple perspectives'],
    parentTip: 'Discuss current events and ask for their opinions',
  },
  // Language
  {
    id: 'sch-lang-1',
    title: 'Communicates complex ideas',
    description: 'Expresses detailed thoughts clearly',
    domain: 'language',
    ageGroup: 'school-age',
    order: 1,
    examples: ['Explains ideas in detail', 'Tells elaborate stories'],
    parentTip: 'Have conversations about topics that interest them',
  },
  {
    id: 'sch-lang-2',
    title: 'Reads fluently',
    description: 'Reads grade-level text with comprehension',
    domain: 'language',
    ageGroup: 'school-age',
    order: 2,
    examples: ['Reads chapter books', 'Summarizes what was read'],
    parentTip: 'Continue reading aloud together even as they read independently',
  },
  {
    id: 'sch-lang-3',
    title: 'Writes for different purposes',
    description: 'Produces various types of writing',
    domain: 'language',
    ageGroup: 'school-age',
    order: 3,
    examples: ['Writes stories and reports', 'Composes letters and emails'],
    parentTip: 'Encourage journaling and writing for fun',
  },
  {
    id: 'sch-lang-4',
    title: 'Expands vocabulary',
    description: 'Uses and understands new words',
    domain: 'language',
    ageGroup: 'school-age',
    order: 4,
    examples: ['Uses context to understand words', 'Incorporates new vocabulary'],
    parentTip: 'Introduce and discuss new words regularly',
  },
  // Physical
  {
    id: 'sch-phys-1',
    title: 'Demonstrates athletic skills',
    description: 'Participates in sports and physical activities',
    domain: 'physical',
    ageGroup: 'school-age',
    order: 1,
    examples: ['Plays team sports', 'Develops specific athletic skills'],
    parentTip: 'Support physical activity they enjoy',
  },
  {
    id: 'sch-phys-2',
    title: 'Has refined fine motor skills',
    description: 'Performs detailed hand movements',
    domain: 'physical',
    ageGroup: 'school-age',
    order: 2,
    examples: ['Writes legibly', 'Creates detailed art projects'],
    parentTip: 'Encourage crafts, building, and hands-on activities',
  },
  {
    id: 'sch-phys-3',
    title: 'Manages personal health',
    description: 'Takes responsibility for self-care',
    domain: 'physical',
    ageGroup: 'school-age',
    order: 3,
    examples: ['Maintains hygiene independently', 'Makes healthy food choices'],
    parentTip: 'Give increasing responsibility for health decisions',
  },
  // Social-Emotional
  {
    id: 'sch-se-1',
    title: 'Builds friendships',
    description: 'Develops and maintains peer relationships',
    domain: 'social-emotional',
    ageGroup: 'school-age',
    order: 1,
    examples: ['Has close friends', 'Resolves conflicts with peers'],
    parentTip: 'Support friendships through playdates and activities',
  },
  {
    id: 'sch-se-2',
    title: 'Shows responsibility',
    description: 'Takes ownership of tasks and belongings',
    domain: 'social-emotional',
    ageGroup: 'school-age',
    order: 2,
    examples: ['Completes chores', 'Manages homework independently'],
    parentTip: 'Assign age-appropriate responsibilities',
  },
  {
    id: 'sch-se-3',
    title: 'Demonstrates resilience',
    description: 'Copes with challenges and setbacks',
    domain: 'social-emotional',
    ageGroup: 'school-age',
    order: 3,
    examples: ['Bounces back from disappointment', 'Perseveres through difficulty'],
    parentTip: 'Praise effort over outcome and normalize mistakes',
  },
  {
    id: 'sch-se-4',
    title: 'Understands perspective',
    description: 'Considers others\' viewpoints',
    domain: 'social-emotional',
    ageGroup: 'school-age',
    order: 4,
    examples: ['Sees situations from others\' views', 'Shows compassion'],
    parentTip: 'Discuss how others might feel in different situations',
  },
  // Creative
  {
    id: 'sch-cre-1',
    title: 'Pursues creative interests',
    description: 'Develops skills in chosen creative areas',
    domain: 'creative',
    ageGroup: 'school-age',
    order: 1,
    examples: ['Takes art or music lessons', 'Creates independently'],
    parentTip: 'Support and provide resources for creative interests',
  },
  {
    id: 'sch-cre-2',
    title: 'Thinks creatively',
    description: 'Generates original ideas and solutions',
    domain: 'creative',
    ageGroup: 'school-age',
    order: 2,
    examples: ['Invents games', 'Creates original stories or art'],
    parentTip: 'Value and encourage original thinking',
  },
  {
    id: 'sch-cre-3',
    title: 'Appreciates arts and culture',
    description: 'Shows interest in various art forms',
    domain: 'creative',
    ageGroup: 'school-age',
    order: 3,
    examples: ['Enjoys music and performances', 'Visits museums'],
    parentTip: 'Expose children to diverse cultural experiences',
  },
  // Literacy/Math combined for school age
  {
    id: 'sch-lit-1',
    title: 'Reads for information and pleasure',
    description: 'Uses reading for various purposes',
    domain: 'literacy',
    ageGroup: 'school-age',
    order: 1,
    examples: ['Researches topics of interest', 'Chooses books independently'],
    parentTip: 'Keep a variety of reading materials available',
  },
  {
    id: 'sch-lit-2',
    title: 'Writes with structure',
    description: 'Organizes writing with beginning, middle, end',
    domain: 'literacy',
    ageGroup: 'school-age',
    order: 2,
    examples: ['Writes paragraphs', 'Uses punctuation and grammar'],
    parentTip: 'Encourage writing through journals or letters',
  },
  {
    id: 'sch-math-1',
    title: 'Performs mathematical operations',
    description: 'Adds, subtracts, multiplies, and divides',
    domain: 'math',
    ageGroup: 'school-age',
    order: 1,
    examples: ['Solves multi-digit problems', 'Uses mental math strategies'],
    parentTip: 'Practice math in everyday situations like shopping',
  },
  {
    id: 'sch-math-2',
    title: 'Applies math concepts',
    description: 'Uses math in real-world situations',
    domain: 'math',
    ageGroup: 'school-age',
    order: 2,
    examples: ['Calculates money', 'Measures ingredients when cooking'],
    parentTip: 'Involve children in cooking, budgeting, and measuring',
  },
  {
    id: 'sch-math-3',
    title: 'Understands fractions and decimals',
    description: 'Works with parts of whole numbers',
    domain: 'math',
    ageGroup: 'school-age',
    order: 3,
    examples: ['Divides pizza into equal parts', 'Understands money decimals'],
    parentTip: 'Use cooking and sharing to practice fractions',
  },
];

// Helper function to get milestones by age group
export function getMilestonesByAgeGroup(ageGroup: string): Milestone[] {
  return MILESTONES.filter(m => m.ageGroup === ageGroup).sort((a, b) => a.order - b.order);
}

// Helper function to get milestones by domain within an age group
export function getMilestonesByDomain(ageGroup: string, domain: LearningDomain): Milestone[] {
  return MILESTONES.filter(m => m.ageGroup === ageGroup && m.domain === domain).sort((a, b) => a.order - b.order);
}

// Helper function to get domain overview
export function getDomainOverview(domain: LearningDomain): DomainOverview | undefined {
  return DOMAIN_OVERVIEWS.find(d => d.domain === domain);
}
