import { TrainingModule } from '@/types/training';

export const trainingModules: TrainingModule[] = [
  // UNIT 1: Getting Started
  {
    id: 'M01',
    number: 1,
    unitId: 'unit-1',
    title: 'Welcome and Login',
    format: 'Self-paced (5 min)',
    durationMinutes: 5,
    roles: ['parent', 'teacher', 'admin', 'owner'],
    contextBridge: 'The gateway to everything. Every other module starts here.',
    completionBridge: 'You can log in. Now learn where everything lives inside your portal.',
    portalPages: ['/login', '/admin-login', '/employee-login', '/kiosk'],
    learningOutcomes: [
      'Log in to the correct portal for your role',
      'Understand what role-based access means',
      'Reset your PIN or password without calling for help',
    ],
    costImpact: 'Every login support call costs 5-10 minutes of director time. With 15 staff, that adds up to 2.5 hours monthly.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M02',
    number: 2,
    unitId: 'unit-1',
    title: 'Navigating Your Portal',
    format: 'Self-paced (10 min)',
    durationMinutes: 10,
    roles: ['parent', 'teacher', 'admin', 'owner'],
    contextBridge: 'Know where everything lives before you start using it.',
    completionBridge: 'You know the layout. Now make your profile accurate so the system works for you.',
    portalPages: ['/admin', '/employee', '/dashboard'],
    learningOutcomes: [
      'Find any page within 2 clicks from your dashboard',
      'Understand the portal layout: sidebar (desktop) and bottom tabs (mobile)',
      'Use quick-action buttons for common tasks',
    ],
    costImpact: 'Reduces "where do I find X?" questions by roughly 80%.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M03',
    number: 3,
    unitId: 'unit-1',
    title: 'Your Profile and Settings',
    format: 'Self-paced (10 min)',
    durationMinutes: 10,
    roles: ['parent', 'teacher', 'admin', 'owner'],
    contextBridge: 'Accurate profiles protect children. Allergies, contacts, permissions.',
    completionBridge: 'Your profile is complete. Now learn the kiosk that families touch every day.',
    portalPages: ['/employee/profile', '/dashboard', '/admin/settings'],
    learningOutcomes: [
      'Update personal information (address, phone, photo)',
      'Manage emergency contacts',
      'Set notification preferences',
      'Upload a profile photo',
    ],
    costImpact: 'Every incomplete profile is a licensing risk. Staff chase down info manually at 15 min per family.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M04',
    number: 4,
    unitId: 'unit-1',
    title: 'Kiosk Check-In/Check-Out',
    format: 'Facilitated (5 min)',
    durationMinutes: 5,
    roles: ['parent', 'teacher', 'admin'],
    contextBridge: 'The first thing families touch every day. Confidence here sets the tone.',
    completionBridge: 'You can check in and out confidently. The data you create here feeds attendance, ratios, and meal counts.',
    portalPages: ['/kiosk'],
    learningOutcomes: [
      'Enter your PIN on the iPad kiosk',
      'Check in and check out each child or yourself',
      'Understand the auto-reset timer',
    ],
    costImpact: 'Accurate attendance drives CACFP reimbursement. A 5% error rate costs $2,000-$4,000/year in lost claims.',
    hasKnowledgeCheck: false,
  },

  // UNIT 2: Daily Rhythms
  {
    id: 'M05',
    number: 5,
    unitId: 'unit-2',
    title: 'Attendance Tracking',
    format: 'Self-paced (15 min) + Facilitated (30 min)',
    durationMinutes: 45,
    roles: ['teacher', 'admin', 'owner'],
    contextBridge: 'Real-time attendance drives ratio compliance and meal count accuracy.',
    completionBridge: 'You can track attendance. Now learn meal counts, which turn that data into revenue.',
    portalPages: ['/admin/attendance', '/admin/ratios'],
    learningOutcomes: [
      'View real-time attendance by classroom',
      'Identify absent children and understand ratio implications',
      'Understand how attendance changes affect staffing needs',
    ],
    costImpact: 'Inaccurate attendance creates licensing violations ($500-$5,000 fines) and lost CACFP claims.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M06',
    number: 6,
    unitId: 'unit-2',
    title: 'Meal Count Submission',
    format: 'Self-paced (15 min) + Facilitated (45 min)',
    durationMinutes: 60,
    roles: ['teacher', 'admin', 'owner'],
    contextBridge: 'Every missed count costs the center money. This protects CACFP revenue.',
    completionBridge: 'You protect revenue with every count you submit. Now learn to capture the moments families care about.',
    portalPages: ['/admin/food-counts', '/employee/meal-count', '/admin/compliance'],
    learningOutcomes: [
      'Submit meal counts before each deadline',
      'Use the pre-fill feature to save time',
      'Understand why counts equal money: each count triggers a reimbursement claim',
    ],
    costImpact: 'Single highest-impact module. Missing one meal count/week loses $6,000-$16,000/year.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M07',
    number: 7,
    unitId: 'unit-2',
    title: 'Daily Photo Upload',
    format: 'Self-paced (10 min)',
    durationMinutes: 10,
    roles: ['teacher', 'admin'],
    contextBridge: 'Parents who see daily photos stay enrolled. Three photos per shift.',
    completionBridge: 'Photos build trust. Now learn task management to keep the rest of your day organized.',
    portalPages: ['/employee/photos', '/admin/communications/photos', '/dashboard/photos'],
    learningOutcomes: [
      'Upload photos with activity tags',
      'Write brief captions for parents',
      'Understand the approval workflow',
      'Batch upload up to 5 photos at once',
    ],
    costImpact: 'Families seeing daily photos are 40% less likely to leave. Retaining 2 families/year = $19,000-$29,000.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M08',
    number: 8,
    unitId: 'unit-2',
    title: 'Task Management',
    format: 'Self-paced (15 min) + Facilitated (30 min)',
    durationMinutes: 45,
    roles: ['teacher', 'admin', 'owner'],
    contextBridge: 'Clear tasks replace sticky notes. Priority and time block keep the day moving.',
    completionBridge: 'Tasks are organized. Now see how daily reports pull everything together for families.',
    portalPages: ['/admin/tasks', '/employee/tasks', '/employee/nap-tasks'],
    learningOutcomes: [
      'View assigned tasks organized by time block',
      'Mark tasks complete with a timestamp',
      'Understand priority levels',
      'Use the nap-time optimizer',
    ],
    costImpact: 'Delegation engine saves the owner 5-10 hours/week.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M09',
    number: 9,
    unitId: 'unit-2',
    title: 'Daily Reports',
    format: 'Self-paced (10 min)',
    durationMinutes: 10,
    roles: ['parent', 'teacher', 'admin', 'owner'],
    contextBridge: 'The summary families see at pickup. What their child ate, how nap went, what happened.',
    completionBridge: 'Daily reports close the loop. Now learn direct messaging to build deeper family relationships.',
    portalPages: ['/admin/reports/daily', '/dashboard'],
    learningOutcomes: [
      'View per-child daily summaries',
      'Understand what parents see on their end',
      'Filter reports by classroom and date',
    ],
    costImpact: 'Reduces parent anxiety calls by ~60%. Professional reports are a competitive differentiator.',
    hasKnowledgeCheck: false,
  },

  // UNIT 3: Communication & Family Engagement
  {
    id: 'M10',
    number: 10,
    unitId: 'unit-3',
    title: 'Parent-Staff Messaging',
    format: 'Self-paced (10 min)',
    durationMinutes: 10,
    roles: ['parent', 'teacher', 'admin', 'owner'],
    contextBridge: 'Direct communication builds trust. Response within 4 hours keeps families confident.',
    completionBridge: 'One-on-one messaging works. Now learn newsletters to reach all families at once.',
    portalPages: ['/admin/messaging', '/dashboard/messages'],
    learningOutcomes: [
      'Send and receive messages through the platform',
      'View conversation history',
      'Understand response time expectations (within 4 hours)',
    ],
    costImpact: 'Documented communication builds trust and protects both parties if disagreements arise.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M11',
    number: 11,
    unitId: 'unit-3',
    title: 'Newsletters and Announcements',
    format: 'Self-paced (20 min) + Facilitated (30 min)',
    durationMinutes: 50,
    roles: ['admin', 'owner'],
    contextBridge: 'Informed families stay enrolled. Weekly updates make the center feel professional.',
    completionBridge: 'Newsletters reach everyone. Now learn the parent portal from their perspective.',
    portalPages: ['/admin/news', '/admin/communications', '/dashboard/news'],
    learningOutcomes: [
      'Create a newsletter with multiple sections',
      'Schedule a send time',
      'View read receipts',
      'Use templates to save time',
    ],
    costImpact: 'Consistent newsletters reduce "I didn\'t know" complaints and project professionalism.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M12',
    number: 12,
    unitId: 'unit-3',
    title: 'Parent Portal Mastery',
    format: 'Self-paced (15 min)',
    durationMinutes: 15,
    roles: ['parent'],
    contextBridge: 'Everything families can do in one place. Photos, messages, calendar, profile.',
    completionBridge: 'You know every feature available to you. Now customize your notifications so you get what matters.',
    portalPages: ['/dashboard', '/dashboard/photos', '/dashboard/progress', '/dashboard/children', '/dashboard/documents', '/dashboard/calendar'],
    learningOutcomes: [
      'View your child\'s daily photos and progress reports',
      'Check the center calendar',
      'Update family information without calling the office',
      'Manage notification preferences',
    ],
    costImpact: 'Self-service saves ~15 min per family per update cycle. Across 40 families quarterly = 40 hours saved/year.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M13',
    number: 13,
    unitId: 'unit-3',
    title: 'Notification Management',
    format: 'Self-paced (5 min)',
    durationMinutes: 5,
    roles: ['parent', 'teacher'],
    contextBridge: 'Control what alerts you get and how. Keep the important ones, silence the noise.',
    completionBridge: 'Notifications are tuned. Communication is working. Time to focus on compliance and safety.',
    portalPages: ['/dashboard/notifications', '/admin/notifications'],
    learningOutcomes: [
      'Configure which notifications you receive',
      'Understand notification types',
      'Manage preferences for right information at right time',
    ],
    costImpact: 'Right notifications = right actions. Too many = ignored. Getting the balance right determines system adoption.',
    hasKnowledgeCheck: false,
  },

  // UNIT 4: Compliance & Safety
  {
    id: 'M14',
    number: 14,
    unitId: 'unit-4',
    title: 'CACFP Compliance Deep Dive',
    format: 'Facilitated (60 min)',
    durationMinutes: 60,
    roles: ['admin', 'owner'],
    contextBridge: 'Reimbursement can be $40,000-80,000 per year. A failed audit suspends that income.',
    completionBridge: 'CACFP is protected. Now learn ratio monitoring to keep children safe and the license secure.',
    portalPages: ['/admin/compliance', '/admin/food-counts'],
    learningOutcomes: [
      'Interpret the compliance dashboard: green, yellow, red',
      'Achieve and maintain 90%+ audit readiness',
      'Understand reimbursement calculations',
      'Generate compliance reports for auditors on demand',
    ],
    costImpact: 'CACFP audit failure suspends $40,000-$80,000/year in reimbursement. Recovery takes months.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M15',
    number: 15,
    unitId: 'unit-4',
    title: 'Ratio Monitoring and Compliance',
    format: 'Self-paced (15 min) + Facilitated (30 min)',
    durationMinutes: 45,
    roles: ['teacher', 'admin', 'owner'],
    contextBridge: 'Ratios keep children safe. The dashboard shows violations before they become citations.',
    completionBridge: 'Ratios are monitored. Now learn incident reporting for when things go wrong despite prevention.',
    portalPages: ['/admin/ratios', '/admin/attendance'],
    learningOutcomes: [
      'Read the ratio dashboard instantly',
      'Understand Minnesota state ratio requirements by age group',
      'Respond to ratio violations: who to call, how to rebalance',
      'Know when a ratio issue becomes licensure-reportable',
    ],
    costImpact: 'Ratio violations cost $500-$5,000 in fines. Repeated violations risk conditional licensing or closure.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M16',
    number: 16,
    unitId: 'unit-4',
    title: 'Incident Reporting',
    format: 'Facilitated (45 min)',
    durationMinutes: 45,
    roles: ['teacher', 'admin', 'owner'],
    contextBridge: 'File within 30 minutes. Facts only. Every edit is tracked.',
    completionBridge: 'Incidents are documented properly. Now learn certification tracking to prevent compliance gaps.',
    portalPages: ['/admin/incidents', '/admin/incidents/log', '/admin/incidents/training'],
    learningOutcomes: [
      'File a complete incident report with all required fields',
      'Assign the correct severity level',
      'Notify parents through the system',
      'Understand the audit trail',
      'Know which incidents are licensure-reportable',
    ],
    costImpact: 'Undocumented incidents create $10,000-$100,000 in liability exposure.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M17',
    number: 17,
    unitId: 'unit-4',
    title: 'Certifications and Training Tracking',
    format: 'Self-paced (10 min)',
    durationMinutes: 10,
    roles: ['teacher', 'admin', 'owner'],
    contextBridge: 'An expired certification means a staff member cannot legally work in ratio.',
    completionBridge: 'Certifications are tracked. Compliance is solid. Time for scheduling and staff management.',
    portalPages: ['/employee/training', '/employee/development', '/admin/staff/development'],
    learningOutcomes: [
      'View your certification status and expiration dates',
      'Understand the alert system: 90, 60, and 30 days before expiration',
      'Log training hours and upload certificates',
      'Request training through the system',
    ],
    costImpact: 'Expired certifications mean scrambling for coverage and potential licensing findings.',
    hasKnowledgeCheck: true,
  },

  // UNIT 5: Scheduling & Staff Management
  {
    id: 'M18',
    number: 18,
    unitId: 'unit-5',
    title: 'Staff Scheduling',
    format: 'Facilitated (60 min)',
    durationMinutes: 60,
    roles: ['admin', 'owner'],
    contextBridge: 'Build a compliant schedule that meets ratios and stays under budget.',
    completionBridge: 'Schedules are optimized. Now learn HR documentation to protect the center.',
    portalPages: ['/admin/scheduling', '/admin/schedule-optimizer', '/employee/schedule'],
    learningOutcomes: [
      'Build a weekly schedule using drag-and-drop',
      'Check ratio compliance for every time block',
      'Project weekly labor costs before publishing',
      'Handle coverage requests',
      'Publish to staff phones',
    ],
    costImpact: 'Optimized scheduling reduces overtime 15-20%, saving $10,000+/year.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M19',
    number: 19,
    unitId: 'unit-5',
    title: 'HR and Document Management',
    format: 'Self-paced (20 min)',
    durationMinutes: 20,
    roles: ['admin', 'owner'],
    contextBridge: 'Written records protect the center. File all actions the same day they happen.',
    completionBridge: 'HR is documented. Now learn payroll management to close the staff operations loop.',
    portalPages: ['/admin/hr', '/admin/staff'],
    learningOutcomes: [
      'Create HR documents from templates',
      'Track document status through the workflow',
      'Manage discipline records with proper documentation',
      'Maintain complete employee files for licensing',
    ],
    costImpact: 'Proper HR docs protect against wrongful termination claims ($10,000-$50,000 per incident).',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M20',
    number: 20,
    unitId: 'unit-5',
    title: 'Payroll Management',
    format: 'Self-paced (20 min) + Facilitated (30 min)',
    durationMinutes: 50,
    roles: ['owner'],
    contextBridge: 'Process payroll with correct calculations. Catch overtime before it happens.',
    completionBridge: 'Payroll runs clean. Now learn onboarding so new hires ramp up fast.',
    portalPages: ['/admin/payroll', '/employee/pay-stubs'],
    learningOutcomes: [
      'Review time entries from kiosk and manual clock-ins',
      'Generate pay stubs with correct calculations',
      'Identify and flag overtime before it hits the paycheck',
      'Reconcile hours between schedule and actual clock data',
      'Approve payroll before it processes',
    ],
    costImpact: 'Catching time entry errors saves 2-5% of labor costs ($4,000-$10,000/year).',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M21',
    number: 21,
    unitId: 'unit-5',
    title: 'Staff Onboarding',
    format: 'Self-paced (15 min) + Facilitated (45 min)',
    durationMinutes: 60,
    roles: ['admin', 'owner'],
    contextBridge: 'New hires get a structured checklist. Background check to certification in one pathway.',
    completionBridge: 'Onboarding is systematic. Staff management is complete. Time to grow enrollment.',
    portalPages: ['/admin/hr/onboarding', '/employee/onboarding'],
    learningOutcomes: [
      'Create a digital onboarding pathway with phased tasks',
      'Assign checklist tasks with due dates and verification',
      'Track new hire progress from admin view',
      'Ensure all compliance items completed on time',
    ],
    costImpact: 'Structured onboarding reduces first-year turnover by 25%. Each replacement costs $3,000-$5,000.',
    hasKnowledgeCheck: true,
  },

  // UNIT 6: Growth & Enrollment
  {
    id: 'M22',
    number: 22,
    unitId: 'unit-6',
    title: 'Enrollment Pipeline',
    format: 'Self-paced (15 min) + Facilitated (45 min)',
    durationMinutes: 60,
    roles: ['admin', 'owner'],
    contextBridge: 'Each enrolled child is $800-1,200 per month. Converting 2 extra leads per quarter adds $20,000+.',
    completionBridge: 'The pipeline is active. Now learn tour management to convert prospects in person.',
    portalPages: ['/admin/pipeline', '/admin/pipeline/enrollment', '/admin/inquiries'],
    learningOutcomes: [
      'Track every prospect through the funnel',
      'Identify stalled leads and take action',
      'Understand conversion rates between stages',
      'Set follow-up reminders',
    ],
    costImpact: 'Converting 2 extra leads/quarter adds $20,000-$30,000/year.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M23',
    number: 23,
    unitId: 'unit-6',
    title: 'Tour Management',
    format: 'Self-paced (10 min) + Facilitated (30 min)',
    durationMinutes: 40,
    roles: ['admin', 'owner'],
    contextBridge: 'Respond within 24 hours. Follow up within 48 hours. The pipeline is revenue.',
    completionBridge: 'Tours convert prospects. Now track authorizations to protect the revenue they generate.',
    portalPages: ['/admin/pipeline/tours', '/schedule-tour'],
    learningOutcomes: [
      'Schedule tours using the calendar system',
      'Use the digital tour checklist during visits',
      'Enable parent self-scheduling via public website',
      'Send follow-up templates within 2 hours',
    ],
    costImpact: 'Standardized tours convert 30% better. One extra family/quarter = $10,000-$14,000/year.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M24',
    number: 24,
    unitId: 'unit-6',
    title: 'Authorization Tracking',
    format: 'Self-paced (15 min)',
    durationMinutes: 15,
    roles: ['admin', 'owner'],
    contextBridge: 'Expiring authorizations mean expiring revenue. The dashboard shows what is at risk.',
    completionBridge: 'Authorizations are monitored. Now learn website management to keep the top of the funnel full.',
    portalPages: ['/admin/pipeline/authorizations'],
    learningOutcomes: [
      'Monitor state authorization status for every enrolled child',
      'Respond to expiry alerts at 60, 30, and 14 day marks',
      'Track renewal processing',
      'Understand revenue-at-risk calculations',
    ],
    costImpact: 'Lapsed authorizations for 2 children/quarter = $3,200-$7,200 in lost revenue.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M25',
    number: 25,
    unitId: 'unit-6',
    title: 'Public Website and Marketing',
    format: 'Self-paced (15 min)',
    durationMinutes: 15,
    roles: ['owner'],
    contextBridge: 'The public face of the center. Where inquiries start before they become enrollments.',
    completionBridge: 'Growth tools are complete. Time for financial intelligence to manage the money all this generates.',
    portalPages: ['/', '/about', '/programs', '/gallery', '/enroll'],
    learningOutcomes: [
      'Understand what families see on the public website',
      'Manage enrollment form submissions',
      'Keep gallery photos and program descriptions current',
    ],
    costImpact: 'A professional web presence reduces cost per lead compared to paid advertising.',
    hasKnowledgeCheck: false,
  },

  // UNIT 7: Financial Intelligence
  {
    id: 'M26',
    number: 26,
    unitId: 'unit-7',
    title: 'Budget Planning and Tracking',
    format: 'Facilitated (60 min)',
    durationMinutes: 60,
    roles: ['owner'],
    contextBridge: 'Set budgets by category. Review actuals monthly. Catch variances before they compound.',
    completionBridge: 'Budget is tracked. Now learn forecasting to see what is coming before it arrives.',
    portalPages: ['/admin/budget', '/admin/financial'],
    learningOutcomes: [
      'Set an annual budget by category',
      'Track actual spending against budget monthly',
      'Interpret variance reports',
      'Export data to Excel for your accountant',
      'Compare budget performance across both sites',
    ],
    costImpact: 'Monthly tracking catches overspending 6 weeks earlier than quarterly review.',
    hasKnowledgeCheck: true,
  },
  {
    id: 'M27',
    number: 27,
    unitId: 'unit-7',
    title: 'Revenue Forecasting',
    format: 'Facilitated (45 min)',
    durationMinutes: 45,
    roles: ['owner'],
    contextBridge: 'Run what-if scenarios. What happens if 3 children leave? What if CACFP drops?',
    completionBridge: 'You can see the future financially. Now learn to find the leaks and plug them.',
    portalPages: ['/admin/financial/forecasting'],
    learningOutcomes: [
      'Read revenue projections based on current enrollment',
      'Run what-if scenarios',
      'Understand the P&L statement the system generates',
      'Interpret optimization suggestions',
    ],
    costImpact: 'Proactive forecasting prevents cash flow surprises. The most expensive problem is a slow leak you don\'t notice.',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M28',
    number: 28,
    unitId: 'unit-7',
    title: 'Cost Optimization',
    format: 'Facilitated (45 min)',
    durationMinutes: 45,
    roles: ['owner'],
    contextBridge: 'Platform data shows where money leaks. Identify 3 opportunities per quarter.',
    completionBridge: 'Financial intelligence is complete. Time for strategic leadership across both centers.',
    portalPages: ['/admin/financial', '/admin/budget', '/admin/supplies'],
    learningOutcomes: [
      'Interpret expense breakdown by category',
      'Identify optimization opportunities in staffing, CACFP, and supplies',
      'Understand labor cost as percentage of revenue (healthy = 50-55%)',
      'Challenge assumptions about spending',
    ],
    costImpact: 'Typical first-year savings from data-driven cost management: $15,000-$30,000.',
    hasKnowledgeCheck: false,
  },

  // UNIT 8: Strategic Leadership
  {
    id: 'M29',
    number: 29,
    unitId: 'unit-8',
    title: 'Cross-Site Operations',
    format: 'Self-paced (15 min) + Facilitated (45 min)',
    durationMinutes: 60,
    roles: ['owner'],
    contextBridge: 'Monitor both centers from one screen. Compare metrics, share staff, standardize quality.',
    completionBridge: 'You see both centers clearly. Now turn that visibility into strategic action.',
    portalPages: ['/admin/operations', '/admin'],
    learningOutcomes: [
      'Monitor both centers from a single screen',
      'Compare performance metrics side by side',
      'Identify trends one center shows but the other does not',
      'Manage by exception: focus on what needs attention',
    ],
    costImpact: 'Cross-site dashboard saves 10+ hours/week in travel and status calls ($500-$1,000/week in owner time).',
    hasKnowledgeCheck: false,
  },
  {
    id: 'M30',
    number: 30,
    unitId: 'unit-8',
    title: 'Strategic Planning',
    format: 'Facilitated (90 min)',
    durationMinutes: 90,
    roles: ['owner'],
    contextBridge: 'Move from someday to tracked priorities with deadlines and accountability dates.',
    completionBridge: 'You have completed the full training pathway. The platform is yours to run.',
    portalPages: ['/admin/strategic', '/admin/meetings', '/admin/meetings/efficiency'],
    learningOutcomes: [
      'Define mission, vision, and values in the system',
      'Conduct a SWOT analysis using platform data',
      'Set strategic priorities with timelines and accountability',
      'Use the meeting efficiency tool',
      'Create a cycle of continuous improvement',
    ],
    costImpact: 'Centers with strategic plans grow enrollment 20% faster than reactive ones.',
    hasKnowledgeCheck: false,
  },
];

export function getModuleById(moduleId: string): TrainingModule | undefined {
  return trainingModules.find(m => m.id === moduleId);
}

export function getModulesForUnit(unitId: string): TrainingModule[] {
  return trainingModules.filter(m => m.unitId === unitId);
}

export function getModuleIndex(moduleId: string): number {
  return trainingModules.findIndex(m => m.id === moduleId);
}

export function getNextModule(moduleId: string, roleModules: string[]): TrainingModule | undefined {
  const currentIndex = roleModules.indexOf(moduleId);
  if (currentIndex === -1 || currentIndex >= roleModules.length - 1) return undefined;
  return getModuleById(roleModules[currentIndex + 1]);
}

export function getPreviousModule(moduleId: string, unitId: string): TrainingModule | undefined {
  const unitModules = getModulesForUnit(unitId);
  const idx = unitModules.findIndex(m => m.id === moduleId);
  if (idx <= 0) return undefined;
  return unitModules[idx - 1];
}
