import { KnowledgeQuestion } from '@/types/training';

export const trainingQuestions: KnowledgeQuestion[] = [
  // ============================================================
  // M05: Attendance Tracking (5 Questions)
  // ============================================================
  {
    id: 'M05-Q01',
    moduleId: 'M05',
    questionText: 'A parent calls at 10:15 AM to say their child will not be coming today. What should you do first in the system?',
    choices: [
      { label: 'A', text: 'Wait until end of day to mark absent' },
      { label: 'B', text: 'Mark the child absent immediately and note the reason' },
      { label: 'C', text: 'Ask the parent to call back later' },
      { label: 'D', text: "Delete the child from today's roster" },
    ],
    correctAnswer: 'B',
    explanation: 'Marking absent immediately updates the real-time attendance count, which affects ratio calculations and CACFP meal count accuracy for the rest of the day.',
  },
  {
    id: 'M05-Q02',
    moduleId: 'M05',
    questionText: 'You notice the attendance dashboard shows 14 children in the toddler room, but you count 13 in the room. What is the most likely cause?',
    choices: [
      { label: 'A', text: 'The system is broken' },
      { label: 'B', text: 'A child checked in at the kiosk but was picked up without checking out' },
      { label: 'C', text: 'You miscounted' },
      { label: 'D', text: 'A child from another room was transferred' },
    ],
    correctAnswer: 'B',
    explanation: 'The most common attendance discrepancy happens when a parent picks up a child without completing the kiosk check-out. This is why staff should verify attendance at every transition.',
  },
  {
    id: 'M05-Q03',
    moduleId: 'M05',
    questionText: 'When should you check the attendance dashboard each day?',
    choices: [
      { label: 'A', text: 'Only when a parent asks' },
      { label: 'B', text: 'At 9:30 AM after the arrival window closes' },
      { label: 'C', text: 'At the end of the day when filing reports' },
      { label: 'D', text: 'Only on Mondays' },
    ],
    correctAnswer: 'B',
    explanation: 'The 9:30 AM check catches discrepancies while there is still time to contact families and correct records before meal counts are submitted.',
  },
  {
    id: 'M05-Q04',
    moduleId: 'M05',
    questionText: 'Why does accurate attendance matter for CACFP reimbursement?',
    choices: [
      { label: 'A', text: 'It does not; CACFP uses enrollment numbers' },
      { label: 'B', text: 'Meal counts must match children who were actually present and served' },
      { label: 'C', text: 'The state only reimburses for children who arrive before 8 AM' },
      { label: 'D', text: 'Attendance only matters for school-age children' },
    ],
    correctAnswer: 'B',
    explanation: 'CACFP reimburses only for meals served to children who are present. Claiming a meal for a child marked absent is a compliance violation that can trigger an audit finding.',
  },
  {
    id: 'M05-Q05',
    moduleId: 'M05',
    questionText: 'Two staff called in sick and the toddler room has 12 children checked in. What is the first thing you should check in the system?',
    choices: [
      { label: 'A', text: 'The newsletter schedule' },
      { label: 'B', text: 'The ratio dashboard to see if you are still in compliance' },
      { label: 'C', text: 'The budget report' },
      { label: 'D', text: 'The photo gallery' },
    ],
    correctAnswer: 'B',
    explanation: 'Staff absences directly affect ratios. With MN toddler ratio at 1:7, 12 toddlers require at least 2 staff. If only 1 remains, you need immediate coverage.',
  },

  // ============================================================
  // M06: Meal Count Submission (10 Questions)
  // ============================================================
  {
    id: 'M06-Q01',
    moduleId: 'M06',
    questionText: 'What is the CACFP reimbursement deadline for submitting breakfast counts?',
    choices: [
      { label: 'A', text: 'Before lunch' },
      { label: 'B', text: 'By 9:30 AM' },
      { label: 'C', text: 'End of the day' },
      { label: 'D', text: 'End of the week' },
    ],
    correctAnswer: 'B',
    explanation: 'Breakfast counts must be submitted by 9:30 AM. Late submissions risk being flagged during audits and may not be reimbursable.',
  },
  {
    id: 'M06-Q02',
    moduleId: 'M06',
    questionText: 'Your center serves 40 children lunch daily. You miss submitting lunch counts for 3 days in one week. Using a $4.50 average reimbursement per child per meal, approximately how much revenue is at risk?',
    choices: [
      { label: 'A', text: '$120' },
      { label: 'B', text: '$270' },
      { label: 'C', text: '$540' },
      { label: 'D', text: '$900' },
    ],
    correctAnswer: 'C',
    explanation: '40 children x $4.50 x 3 days = $540. Over a year, missing just 3 days per week would cost $28,080 in lost reimbursement.',
  },
  {
    id: 'M06-Q03',
    moduleId: 'M06',
    questionText: 'What does the "pre-fill" feature do for meal counts?',
    choices: [
      { label: 'A', text: 'Automatically submits counts without staff input' },
      { label: 'B', text: 'Populates the meal count form with children marked present in attendance' },
      { label: 'C', text: "Fills in last week's numbers" },
      { label: 'D', text: 'Sends the count directly to the state' },
    ],
    correctAnswer: 'B',
    explanation: 'Pre-fill pulls from real-time attendance data so staff only need to adjust for children who were present but did not eat, or who arrived after the initial count.',
  },
  {
    id: 'M06-Q04',
    moduleId: 'M06',
    questionText: 'A child arrives at 10:00 AM, after breakfast was served and counts were submitted. The child\'s parent says they did not eat breakfast at home. What should you do?',
    choices: [
      { label: 'A', text: 'Retroactively add the child to the breakfast count' },
      { label: 'B', text: 'Offer the child a snack and note it; do not alter the submitted breakfast count' },
      { label: 'C', text: 'Ignore the situation' },
      { label: 'D', text: 'Submit a second breakfast count' },
    ],
    correctAnswer: 'B',
    explanation: 'Once a meal count is submitted, altering it to add children who were not present during the meal is a compliance violation. The child can be offered food, but the CACFP count must reflect who was served during the meal period.',
  },
  {
    id: 'M06-Q05',
    moduleId: 'M06',
    questionText: 'Which of the following is NOT one of the four CACFP meal types tracked in the system?',
    choices: [
      { label: 'A', text: 'Breakfast' },
      { label: 'B', text: 'Lunch' },
      { label: 'C', text: 'Dinner' },
      { label: 'D', text: 'PM Snack' },
    ],
    correctAnswer: 'C',
    explanation: 'The four trackable meal types for most child care centers are breakfast, AM snack, lunch, and PM snack. Dinner is only applicable for centers with extended evening hours that have a separate CACFP approval.',
  },
  {
    id: 'M06-Q06',
    moduleId: 'M06',
    questionText: 'You notice a meal count shows 28 children served lunch, but attendance shows only 25 children present. What should you do?',
    choices: [
      { label: 'A', text: 'Submit it anyway; close enough' },
      { label: 'B', text: 'Investigate the discrepancy before submitting' },
      { label: 'C', text: 'Change the attendance to match the meal count' },
      { label: 'D', text: 'Delete the meal count and skip today' },
    ],
    correctAnswer: 'B',
    explanation: 'Meal counts that exceed attendance are audit red flags. The discrepancy could mean attendance was not updated, children from another room were counted twice, or the count was entered incorrectly.',
  },
  {
    id: 'M06-Q07',
    moduleId: 'M06',
    questionText: 'How much revenue does a center with 40 children lose per year if it misses just one meal count per week at $4.50 per child?',
    choices: [
      { label: 'A', text: '$2,340' },
      { label: 'B', text: '$4,680' },
      { label: 'C', text: '$9,360' },
      { label: 'D', text: '$18,720' },
    ],
    correctAnswer: 'C',
    explanation: '40 children x $4.50 x 52 weeks = $9,360 per year from a single missed meal count each week. This is why the system shows deadlines in red when they are approaching.',
  },
  {
    id: 'M06-Q08',
    moduleId: 'M06',
    questionText: 'A new staff member asks why meal counts matter so much. Which response is most accurate?',
    choices: [
      { label: 'A', text: '"It\'s just a state requirement we have to follow."' },
      { label: 'B', text: '"Meal counts are how we get reimbursed through CACFP. Each missed count is money we never get back, and it adds up to thousands per year."' },
      { label: 'C', text: '"The director likes to see the numbers."' },
      { label: 'D', text: '"It helps us order the right amount of food."' },
    ],
    correctAnswer: 'B',
    explanation: 'Staff who understand the financial impact of meal counts are more likely to prioritize timely submission. Framing it as "just a requirement" misses the revenue protection purpose.',
  },
  {
    id: 'M06-Q09',
    moduleId: 'M06',
    questionText: 'The meal count deadline indicator turns yellow. What does this mean?',
    choices: [
      { label: 'A', text: 'The count was submitted successfully' },
      { label: 'B', text: 'The deadline is approaching and the count has not been submitted yet' },
      { label: 'C', text: 'The system is updating' },
      { label: 'D', text: 'A child has an allergy flagged' },
    ],
    correctAnswer: 'B',
    explanation: 'Yellow means the deadline is within range but not yet passed. This is the warning window to submit before the indicator turns red (deadline missed).',
  },
  {
    id: 'M06-Q10',
    moduleId: 'M06',
    questionText: 'During a CACFP audit, the reviewer asks to see meal count records for the past 60 days. Where do you find this in the system?',
    choices: [
      { label: 'A', text: 'The photo gallery' },
      { label: 'B', text: 'The compliance dashboard under CACFP records' },
      { label: 'C', text: 'The parent portal' },
      { label: 'D', text: 'The scheduling module' },
    ],
    correctAnswer: 'B',
    explanation: 'The compliance dashboard stores all submitted meal counts with timestamps, child counts, and submission history. This is the primary audit-ready record.',
  },

  // ============================================================
  // M08: Task Management (5 Questions)
  // ============================================================
  {
    id: 'M08-Q01',
    moduleId: 'M08',
    questionText: 'It is nap time and you have 90 minutes. The task board shows 6 tasks: 2 urgent, 2 normal, 2 low priority. What should you do?',
    choices: [
      { label: 'A', text: 'Start with the easiest tasks to check them off quickly' },
      { label: 'B', text: 'Complete the 2 urgent tasks first, then work through normal priority' },
      { label: 'C', text: 'Skip tasks and take a break since the children are sleeping' },
      { label: 'D', text: 'Ask someone else to do all 6' },
    ],
    correctAnswer: 'B',
    explanation: 'Priority-based task completion ensures critical items (safety checks, meal prep, compliance actions) get done first. The nap window is the primary admin work block for classroom staff.',
  },
  {
    id: 'M08-Q02',
    moduleId: 'M08',
    questionText: 'A director assigns you a task marked "urgent" to restock the first aid kit. You are about to start meal count submission with 10 minutes until deadline. What do you do?',
    choices: [
      { label: 'A', text: 'Restock the first aid kit since it is marked urgent' },
      { label: 'B', text: 'Submit the meal count first because the deadline is imminent, then restock' },
      { label: 'C', text: 'Do neither and wait for further instructions' },
      { label: 'D', text: 'Ask a parent to restock' },
    ],
    correctAnswer: 'B',
    explanation: 'Time-sensitive compliance tasks (meal counts with deadlines) take precedence over urgent but non-time-bound tasks. The meal count deadline is a hard cutoff; the first aid restock can happen 15 minutes later.',
  },
  {
    id: 'M08-Q03',
    moduleId: 'M08',
    questionText: 'What is the purpose of the nap-time task optimizer?',
    choices: [
      { label: 'A', text: 'It puts children to sleep faster' },
      { label: 'B', text: 'It suggests which tasks to complete during the nap window based on priority and estimated time' },
      { label: 'C', text: 'It delays all tasks until naptime' },
      { label: 'D', text: 'It assigns nap duties to staff' },
    ],
    correctAnswer: 'B',
    explanation: 'The optimizer matches available time (nap window duration) with task priority and estimated completion time so staff can make the most of the uninterrupted work block.',
  },
  {
    id: 'M08-Q04',
    moduleId: 'M08',
    questionText: 'You completed a task but forgot to mark it done in the system. Why does this matter?',
    choices: [
      { label: 'A', text: 'It does not matter; the task is done' },
      { label: 'B', text: 'The director will still see it as incomplete, which affects task completion tracking and may trigger follow-up' },
      { label: 'C', text: 'The system will automatically delete it' },
      { label: 'D', text: 'Your pay will be docked' },
    ],
    correctAnswer: 'B',
    explanation: 'Unmarked tasks create false signals. Directors monitoring task boards see incomplete items and may follow up unnecessarily, or worse, assume operational items were missed.',
  },
  {
    id: 'M08-Q05',
    moduleId: 'M08',
    questionText: 'A director delegates a classroom deep-clean task to you for Friday. You have questions about what "deep clean" includes. What should you do?',
    choices: [
      { label: 'A', text: 'Ignore the task' },
      { label: 'B', text: 'Do what you think deep clean means' },
      { label: 'C', text: 'Check the task details in the system for the description and checklist, then ask the director if unclear' },
      { label: 'D', text: 'Wait until Friday and ask then' },
    ],
    correctAnswer: 'C',
    explanation: 'Tasks in the system include descriptions and checklists. Checking there first answers most questions. If the scope is still unclear, asking early gives the director time to clarify before the deadline.',
  },

  // ============================================================
  // M14: CACFP Compliance Deep Dive (10 Questions)
  // ============================================================
  {
    id: 'M14-Q01',
    moduleId: 'M14',
    questionText: 'What is the minimum audit readiness score the center should maintain on the compliance dashboard?',
    choices: [
      { label: 'A', text: '70%' },
      { label: 'B', text: '80%' },
      { label: 'C', text: '90%' },
      { label: 'D', text: '100%' },
    ],
    correctAnswer: 'C',
    explanation: 'The target is 90%+ audit readiness. Below 90% means there are gaps that could result in findings during a state review.',
  },
  {
    id: 'M14-Q02',
    moduleId: 'M14',
    questionText: 'A CACFP auditor arrives unannounced. What is the first thing you should do?',
    choices: [
      { label: 'A', text: 'Ask them to come back next week' },
      { label: 'B', text: 'Welcome them, provide access to the compliance dashboard, and notify the owner immediately' },
      { label: 'C', text: 'Hide any incomplete records' },
      { label: 'D', text: 'Tell them you need to check with your lawyer' },
    ],
    correctAnswer: 'B',
    explanation: 'CACFP audits can be unannounced. Immediate, transparent cooperation demonstrates compliance culture. The digital compliance dashboard provides instant access to records.',
  },
  {
    id: 'M14-Q03',
    moduleId: 'M14',
    questionText: 'How often should the compliance dashboard be reviewed?',
    choices: [
      { label: 'A', text: 'Annually before the audit' },
      { label: 'B', text: 'Every Monday' },
      { label: 'C', text: 'Only when there is a problem' },
      { label: 'D', text: 'Every six months' },
    ],
    correctAnswer: 'B',
    explanation: 'Weekly Monday review catches emerging issues before they compound. Waiting for the annual audit turns small gaps into systemic findings.',
  },
  {
    id: 'M14-Q04',
    moduleId: 'M14',
    questionText: 'Which of the following would be flagged as a CACFP compliance issue?',
    choices: [
      { label: 'A', text: 'Meal counts submitted on time every day' },
      { label: 'B', text: 'Meal counts showing more children served than were marked present' },
      { label: 'C', text: 'A staff member uploading classroom photos' },
      { label: 'D', text: "A parent updating their child's emergency contact" },
    ],
    correctAnswer: 'B',
    explanation: 'Meal counts exceeding attendance is a direct compliance red flag. It suggests either inaccurate attendance tracking or inflated meal counts, both of which can trigger reimbursement suspension.',
  },
  {
    id: 'M14-Q05',
    moduleId: 'M14',
    questionText: "The center's CACFP reimbursement was $72,000 last year. If the audit readiness score drops below 80% and triggers a review, what is the maximum amount at risk?",
    choices: [
      { label: 'A', text: '$7,200' },
      { label: 'B', text: '$36,000' },
      { label: 'C', text: '$72,000' },
      { label: 'D', text: '$144,000' },
    ],
    correctAnswer: 'C',
    explanation: 'A failed audit can result in suspension of the entire CACFP agreement, putting the full reimbursement amount at risk. In severe cases, the center may also need to repay previously claimed amounts.',
  },
  {
    id: 'M14-Q06',
    moduleId: 'M14',
    questionText: 'What documents must be available for a CACFP review? Select the most complete answer.',
    choices: [
      { label: 'A', text: 'Meal counts only' },
      { label: 'B', text: 'Meal counts, attendance records, menus, and income eligibility documentation' },
      { label: 'C', text: 'Staff schedules and payroll' },
      { label: 'D', text: 'Parent satisfaction surveys' },
    ],
    correctAnswer: 'B',
    explanation: 'CACFP reviews examine meal counts cross-referenced with attendance, planned menus compared to actual service, and income eligibility forms for Tier 1 vs Tier 2 classification.',
  },
  {
    id: 'M14-Q07',
    moduleId: 'M14',
    questionText: 'A compliance dashboard item shows "yellow" status for menu documentation. What does this mean?',
    choices: [
      { label: 'A', text: 'Everything is fine' },
      { label: 'B', text: 'The item needs attention soon but is not yet a violation' },
      { label: 'C', text: 'The item has been resolved' },
      { label: 'D', text: 'The menu is approved' },
    ],
    correctAnswer: 'B',
    explanation: 'Yellow is the warning state. It means the issue is approaching non-compliance (e.g., menu not uploaded for next week, documentation expiring soon). Addressing yellow items prevents red violations.',
  },
  {
    id: 'M14-Q08',
    moduleId: 'M14',
    questionText: 'You discover that meal counts for the past two weeks were submitted 30 minutes late every day. What is the impact?',
    choices: [
      { label: 'A', text: 'No impact; they were still submitted the same day' },
      { label: 'B', text: 'Late submissions may not be accepted for reimbursement and create a pattern that auditors flag' },
      { label: 'C', text: 'The system automatically adjusts the timestamps' },
      { label: 'D', text: 'Late counts are worth half the reimbursement' },
    ],
    correctAnswer: 'B',
    explanation: 'Consistent late submissions create audit trail patterns that suggest weak internal controls. While individual late submissions may still be accepted, a pattern triggers heightened scrutiny.',
  },
  {
    id: 'M14-Q09',
    moduleId: 'M14',
    questionText: 'What is the difference between Tier 1 and Tier 2 CACFP reimbursement?',
    choices: [
      { label: 'A', text: 'Tier 1 is for infants only' },
      { label: 'B', text: 'Tier 1 centers receive higher reimbursement rates based on the percentage of children from low-income families in the area' },
      { label: 'C', text: 'Tier 2 pays more than Tier 1' },
      { label: 'D', text: 'There is no difference' },
    ],
    correctAnswer: 'B',
    explanation: 'Tier 1 classification is based on the center\'s location (census data showing high percentage of low-income households) or the percentage of enrolled children receiving public assistance. Tier 1 rates are significantly higher.',
  },
  {
    id: 'M14-Q10',
    moduleId: 'M14',
    questionText: 'The owner asks you to generate a compliance report for the upcoming board meeting. Where do you find this?',
    choices: [
      { label: 'A', text: 'The newsletter module' },
      { label: 'B', text: 'The compliance dashboard export function' },
      { label: 'C', text: 'The parent portal' },
      { label: 'D', text: 'The scheduling module' },
    ],
    correctAnswer: 'B',
    explanation: 'The compliance dashboard includes an export function that generates formatted reports showing audit readiness score, outstanding items, and trend data.',
  },

  // ============================================================
  // M15: Ratio Monitoring & Compliance (10 Questions)
  // ============================================================
  {
    id: 'M15-Q01',
    moduleId: 'M15',
    questionText: 'What is the Minnesota state-required staff-to-child ratio for infants (birth to 16 months)?',
    choices: [
      { label: 'A', text: '1:3' },
      { label: 'B', text: '1:4' },
      { label: 'C', text: '1:7' },
      { label: 'D', text: '1:10' },
    ],
    correctAnswer: 'B',
    explanation: 'Minnesota requires 1 staff for every 4 infants. Maximum group size for infants is 8.',
  },
  {
    id: 'M15-Q02',
    moduleId: 'M15',
    questionText: 'What is the Minnesota state-required ratio for toddlers (16 to 33 months)?',
    choices: [
      { label: 'A', text: '1:4' },
      { label: 'B', text: '1:5' },
      { label: 'C', text: '1:7' },
      { label: 'D', text: '1:10' },
    ],
    correctAnswer: 'C',
    explanation: 'Minnesota requires 1 staff for every 7 toddlers. Maximum group size is 14.',
  },
  {
    id: 'M15-Q03',
    moduleId: 'M15',
    questionText: 'What is the Minnesota state-required ratio for preschool children (33 months to kindergarten)?',
    choices: [
      { label: 'A', text: '1:7' },
      { label: 'B', text: '1:8' },
      { label: 'C', text: '1:10' },
      { label: 'D', text: '1:12' },
    ],
    correctAnswer: 'C',
    explanation: 'Minnesota requires 1 staff for every 10 preschool-age children. Maximum group size is 20.',
  },
  {
    id: 'M15-Q04',
    moduleId: 'M15',
    questionText: 'What is the Minnesota state-required ratio for school-age children?',
    choices: [
      { label: 'A', text: '1:10' },
      { label: 'B', text: '1:12' },
      { label: 'C', text: '1:15' },
      { label: 'D', text: '1:20' },
    ],
    correctAnswer: 'C',
    explanation: 'Minnesota requires 1 staff for every 15 school-age children. Maximum group size is 30.',
  },
  {
    id: 'M15-Q05',
    moduleId: 'M15',
    questionText: 'The toddler room has 13 children and 2 staff. One staff member needs to leave for 10 minutes to handle a parent concern. Are you still in ratio?',
    choices: [
      { label: 'A', text: 'Yes, 1 staff for 13 toddlers is fine' },
      { label: 'B', text: 'No, 1 staff for 13 toddlers exceeds the 1:7 ratio; you need coverage before the staff member leaves' },
      { label: 'C', text: 'It is fine for 10 minutes' },
      { label: 'D', text: 'Ratios only apply during meal times' },
    ],
    correctAnswer: 'B',
    explanation: 'At 1:7, 13 toddlers require 2 staff at all times. There is no grace period for brief absences. A third person must cover before either staff member leaves the room.',
  },
  {
    id: 'M15-Q06',
    moduleId: 'M15',
    questionText: 'A parent drops off their 3-year-old at 8:05 AM. The preschool room currently has 20 children and 2 staff. What happens?',
    choices: [
      { label: 'A', text: 'Accept the child; 21 children with 2 staff is close enough' },
      { label: 'B', text: 'The system flags a ratio violation because 21 children with 2 staff exceeds the 1:10 ratio' },
      { label: 'C', text: 'Send the child to the toddler room' },
      { label: 'D', text: 'Ask the parent to come back in an hour' },
    ],
    correctAnswer: 'B',
    explanation: 'At 1:10, 2 staff can supervise a maximum of 20 preschool children. The 21st child creates an immediate ratio violation. A third staff member must be present before accepting the child into the room.',
  },
  {
    id: 'M15-Q07',
    moduleId: 'M15',
    questionText: 'During afternoon departure, children leave the preschool room over 90 minutes. At what point can you release one of two staff members?',
    choices: [
      { label: 'A', text: 'When the first child leaves' },
      { label: 'B', text: 'When 10 or fewer children remain (because 1 staff can cover 10 at 1:10 ratio)' },
      { label: 'C', text: "Whenever the staff member's shift ends" },
      { label: 'D', text: 'You can never release a staff member during departure' },
    ],
    correctAnswer: 'B',
    explanation: 'Once attendance drops to 10 or fewer preschool children, 1 staff member satisfies the 1:10 ratio. The system should reflect real-time attendance to support this decision.',
  },
  {
    id: 'M15-Q08',
    moduleId: 'M15',
    questionText: 'A licensing inspector asks how you monitor ratios throughout the day. Which answer demonstrates best practice?',
    choices: [
      { label: 'A', text: '"We count heads when we remember."' },
      { label: 'B', text: '"We use real-time digital attendance tracking linked to ratio monitoring, and staff check the dashboard at every transition."' },
      { label: 'C', text: '"We have a paper chart on the wall."' },
      { label: 'D', text: '"The director checks once in the morning."' },
    ],
    correctAnswer: 'B',
    explanation: 'Digital real-time tracking with transition-point checks demonstrates systematic compliance, not sporadic attention.',
  },
  {
    id: 'M15-Q09',
    moduleId: 'M15',
    questionText: 'It is 7:00 AM and only 1 staff member has arrived. 3 infants and 5 toddlers are checked in. Is the center in ratio?',
    choices: [
      { label: 'A', text: 'Yes, 1 staff for 8 children is fine' },
      { label: 'B', text: 'No. 3 infants require 1 staff (at 1:4), and 5 toddlers require 1 staff (at 1:7). You need at least 2 staff.' },
      { label: 'C', text: 'Ratios do not apply before 8 AM' },
      { label: 'D', text: 'Combine the rooms and it is fine' },
    ],
    correctAnswer: 'B',
    explanation: 'Ratios apply from the moment children are in care. Mixed age groups default to the ratio of the youngest children present unless rooms are separated with dedicated staff.',
  },
  {
    id: 'M15-Q10',
    moduleId: 'M15',
    questionText: 'A ratio violation is documented during a licensing visit. What is the potential consequence?',
    choices: [
      { label: 'A', text: 'Nothing; it is just a suggestion' },
      { label: 'B', text: 'A verbal warning with no record' },
      { label: 'C', text: 'A licensing citation that can result in fines of $500 to $5,000 and potential conditional license status' },
      { label: 'D', text: 'Automatic closure of the center' },
    ],
    correctAnswer: 'C',
    explanation: 'Ratio violations are among the most serious licensing findings. Repeated violations can escalate from conditional license to suspension. Fines vary but a single citation commonly costs $500 to $5,000.',
  },

  // ============================================================
  // M16: Incident Reporting (10 Questions)
  // ============================================================
  {
    id: 'M16-Q01',
    moduleId: 'M16',
    questionText: 'A child falls on the playground and scrapes their knee. It is minor, bleeding stopped with a bandaid. Should you file an incident report?',
    choices: [
      { label: 'A', text: 'No, scrapes are normal and do not need documentation' },
      { label: 'B', text: 'Yes, all injuries requiring any first aid must be documented' },
      { label: 'C', text: 'Only if the parent complains' },
      { label: 'D', text: 'Only if the child cries for more than 5 minutes' },
    ],
    correctAnswer: 'B',
    explanation: 'Any injury requiring first aid, regardless of severity, must be documented. This protects the child, the staff, and the center from liability.',
  },
  {
    id: 'M16-Q02',
    moduleId: 'M16',
    questionText: 'How quickly should an incident report be filed after the incident occurs?',
    choices: [
      { label: 'A', text: 'By end of day' },
      { label: 'B', text: 'Within 30 minutes' },
      { label: 'C', text: 'Within 24 hours' },
      { label: 'D', text: 'Before the next licensing visit' },
    ],
    correctAnswer: 'B',
    explanation: 'The 30-minute standard ensures details are fresh and accurate. Delayed reports lose critical details and create liability gaps.',
  },
  {
    id: 'M16-Q03',
    moduleId: 'M16',
    questionText: 'A child bites another child. Which severity level is appropriate?',
    choices: [
      { label: 'A', text: 'Low (no documentation needed)' },
      { label: 'B', text: 'Medium (document, notify both families same day)' },
      { label: 'C', text: 'High (only if skin is broken)' },
      { label: 'D', text: 'Critical (call 911)' },
    ],
    correctAnswer: 'B',
    explanation: "Biting is a medium-severity incident. Both the biting child's family and the bitten child's family must be notified. If the skin is broken, severity escalates and additional medical attention may be needed.",
  },
  {
    id: 'M16-Q04',
    moduleId: 'M16',
    questionText: 'You file an incident report and realize 2 hours later that you got the time wrong. What should you do?',
    choices: [
      { label: 'A', text: 'Delete the report and start over' },
      { label: 'B', text: 'Edit the report; the system tracks all changes in the audit trail' },
      { label: 'C', text: 'Leave it; close enough' },
      { label: 'D', text: 'File a second report with the correct time' },
    ],
    correctAnswer: 'B',
    explanation: 'The system maintains a full audit trail of every edit. Correcting the time is appropriate and transparent. Deleting and recreating would look like evidence tampering to an auditor.',
  },
  {
    id: 'M16-Q05',
    moduleId: 'M16',
    questionText: 'Which of the following incidents is licensure-reportable in Minnesota?',
    choices: [
      { label: 'A', text: 'A child refuses to eat lunch' },
      { label: 'B', text: 'A child is transported to the emergency room from the center' },
      { label: 'C', text: 'A parent is 5 minutes late for pickup' },
      { label: 'D', text: 'A staff member calls in sick' },
    ],
    correctAnswer: 'B',
    explanation: 'Incidents requiring emergency medical transport, allegations of maltreatment, and serious injuries are licensure-reportable. The center must notify the licensing agency within 24 hours.',
  },
  {
    id: 'M16-Q06',
    moduleId: 'M16',
    questionText: "A parent calls at 5:30 PM asking about a bump on their child's forehead. No incident report was filed. What happened, and what should you do?",
    choices: [
      { label: 'A', text: 'Tell the parent it probably happened at home' },
      { label: 'B', text: 'Investigate immediately: ask staff who were in the room, review the timeline, file a late incident report with the actual time and a note explaining the delay' },
      { label: 'C', text: 'Tell the parent you will look into it tomorrow' },
      { label: 'D', text: 'Blame the afternoon staff' },
    ],
    correctAnswer: 'B',
    explanation: 'A late report with honest documentation is far better than no report. The investigation should determine what happened, and the late filing should be noted transparently.',
  },
  {
    id: 'M16-Q07',
    moduleId: 'M16',
    questionText: 'Two children collide heads while running in the gym. One child seems fine; the other is crying and has a visible bump. How many incident reports should you file?',
    choices: [
      { label: 'A', text: 'One, for the child with the bump' },
      { label: 'B', text: 'Two, one for each child involved' },
      { label: 'C', text: 'None, unless a parent asks' },
      { label: 'D', text: 'One combined report' },
    ],
    correctAnswer: 'B',
    explanation: 'Each child involved in an incident gets their own report. The "fine" child may develop symptoms later, and both families need to be informed.',
  },
  {
    id: 'M16-Q08',
    moduleId: 'M16',
    questionText: 'What information must every incident report include?',
    choices: [
      { label: 'A', text: "Just the child's name and what happened" },
      { label: 'B', text: "Child's name, date, time, location, description of what happened, injuries observed, first aid provided, staff present, parent notification status" },
      { label: 'C', text: 'Only injuries that required a doctor visit' },
      { label: 'D', text: "The child's name and a photo" },
    ],
    correctAnswer: 'B',
    explanation: 'Complete incident reports include all contextual details. Missing any element creates a gap that auditors, parents, or attorneys could question.',
  },
  {
    id: 'M16-Q09',
    moduleId: 'M16',
    questionText: 'A staff member witnesses an incident but says, "I\'ll write it up tomorrow, I\'m too busy right now." What should you do?',
    choices: [
      { label: 'A', text: 'That is fine; tomorrow is close enough' },
      { label: 'B', text: 'Offer to help file it now, or file it yourself with available details and have them review within 30 minutes' },
      { label: 'C', text: 'Tell them to forget about it' },
      { label: 'D', text: 'File a complaint about the staff member' },
    ],
    correctAnswer: 'B',
    explanation: 'The 30-minute window is non-negotiable. If the witnessing staff member cannot file immediately, another staff member should initiate the report with available facts.',
  },
  {
    id: 'M16-Q10',
    moduleId: 'M16',
    questionText: 'An incident report shows that the same child has been involved in 5 biting incidents in 2 weeks. What should the director do?',
    choices: [
      { label: 'A', text: 'Nothing; some children bite' },
      { label: 'B', text: 'Review the pattern, schedule a parent conference, develop a behavior plan, and document all steps taken' },
      { label: 'C', text: 'Expel the child' },
      { label: 'D', text: 'Move the child to a different classroom without telling the parents' },
    ],
    correctAnswer: 'B',
    explanation: 'Patterns require systematic response: data review, family partnership, behavior planning, and documentation. Expulsion should be a last resort after documented interventions. Moving without communication damages trust.',
  },

  // ============================================================
  // M17: Certifications & Training Tracking (5 Questions)
  // ============================================================
  {
    id: 'M17-Q01',
    moduleId: 'M17',
    questionText: 'Your CPR certification expires in 45 days. The system sends you a notification. What should you do?',
    choices: [
      { label: 'A', text: 'Wait until it expires, then renew' },
      { label: 'B', text: 'Schedule a renewal class immediately so it is complete before expiration' },
      { label: 'C', text: 'Ignore it; 45 days is plenty of time' },
      { label: 'D', text: 'Ask your director to renew it for you' },
    ],
    correctAnswer: 'B',
    explanation: 'Scheduling immediately prevents last-minute scrambles. If a renewal class fills up or gets canceled, you need buffer time. Expired CPR means you cannot legally be counted in ratios.',
  },
  {
    id: 'M17-Q02',
    moduleId: 'M17',
    questionText: "A staff member's food handler's permit expired last week. What is the immediate operational impact?",
    choices: [
      { label: 'A', text: 'None; they can still work normally' },
      { label: 'B', text: 'They cannot prepare or serve food until renewed, which may require schedule adjustments' },
      { label: 'C', text: 'They get a written warning but continue working' },
      { label: 'D', text: 'The center loses its license' },
    ],
    correctAnswer: 'B',
    explanation: 'Expired food handling certification means the staff member cannot participate in meal prep or service. This creates an operational gap during meal times that must be covered by certified staff.',
  },
  {
    id: 'M17-Q03',
    moduleId: 'M17',
    questionText: 'How far in advance does the system send certification expiry warnings?',
    choices: [
      { label: 'A', text: '7 days only' },
      { label: 'B', text: '90, 60, and 30 days before expiration' },
      { label: 'C', text: 'Only after it expires' },
      { label: 'D', text: '1 year in advance' },
    ],
    correctAnswer: 'B',
    explanation: 'The three-stage warning system (90/60/30 days) gives increasing urgency. The 90-day alert is for planning; the 30-day alert means action is overdue.',
  },
  {
    id: 'M17-Q04',
    moduleId: 'M17',
    questionText: 'Minnesota requires how many annual training hours for child care staff?',
    choices: [
      { label: 'A', text: '4 hours' },
      { label: 'B', text: '8 hours' },
      { label: 'C', text: '16 hours' },
      { label: 'D', text: '24 hours' },
    ],
    correctAnswer: 'C',
    explanation: 'Minnesota requires 16 hours of annual in-service training for child care staff, covering topics like child development, health and safety, and behavior guidance.',
  },
  {
    id: 'M17-Q05',
    moduleId: 'M17',
    questionText: 'The director reviews the certification dashboard and sees that 3 of 8 staff members have certifications expiring within 60 days. What is the priority action?',
    choices: [
      { label: 'A', text: 'Wait and see who renews on their own' },
      { label: 'B', text: 'Create a renewal plan: identify which certifications, find available classes, and schedule coverage for staff attending training' },
      { label: 'C', text: 'Hire 3 new staff members' },
      { label: 'D', text: 'Extend the expiration dates in the system' },
    ],
    correctAnswer: 'B',
    explanation: 'Proactive renewal planning prevents a situation where multiple staff members become non-compliant simultaneously. This includes scheduling coverage so the center stays in ratio while staff attend renewal courses.',
  },

  // ============================================================
  // M18: Staff Scheduling (10 Questions)
  // ============================================================
  {
    id: 'M18-Q01',
    moduleId: 'M18',
    questionText: "Labor costs represent approximately what percentage of a child care center's total expenses?",
    choices: [
      { label: 'A', text: '25%' },
      { label: 'B', text: '40%' },
      { label: 'C', text: '56%' },
      { label: 'D', text: '75%' },
    ],
    correctAnswer: 'C',
    explanation: 'Labor typically represents 56% of child care center expenses. This makes scheduling optimization the single largest lever for cost control.',
  },
  {
    id: 'M18-Q02',
    moduleId: 'M18',
    questionText: "You are building next week's schedule for the toddler room. Enrollment is 14 toddlers with staggered arrivals (7 arrive by 7:30 AM, all 14 by 9:00 AM, departures start at 4:00 PM). What is the minimum staffing pattern?",
    choices: [
      { label: 'A', text: '2 staff all day (7 AM to 6 PM)' },
      { label: 'B', text: '1 staff at open, 2 staff by 9 AM, back to 1 by 4:30 PM when attendance drops below 7' },
      { label: 'C', text: '3 staff all day to be safe' },
      { label: 'D', text: '1 staff all day since toddler ratio is 1:7' },
    ],
    correctAnswer: 'B',
    explanation: 'Staggered staffing aligned to attendance patterns saves labor without violating ratios. Running 2 full shifts when 1 covers the shoulder hours wastes approximately 4 labor hours per day.',
  },
  {
    id: 'M18-Q03',
    moduleId: 'M18',
    questionText: 'A staff member requests Friday off next week. The schedule is already published. What is the correct process?',
    choices: [
      { label: 'A', text: 'Tell them no because the schedule is published' },
      { label: 'B', text: 'Check coverage: review ratios for Friday, find or arrange a substitute, update the schedule, and notify affected staff' },
      { label: 'C', text: 'Grant the day off without checking coverage' },
      { label: 'D', text: 'Delete the published schedule and start over' },
    ],
    correctAnswer: 'B',
    explanation: 'Published schedules can be modified, but changes require coverage verification. The system should show whether removing that staff member creates ratio gaps.',
  },
  {
    id: 'M18-Q04',
    moduleId: 'M18',
    questionText: 'The schedule shows 3 staff members working 42 hours each next week. The owner has a policy of avoiding overtime. What should you adjust?',
    choices: [
      { label: 'A', text: 'Nothing; 42 hours is close enough' },
      { label: 'B', text: 'Restructure shifts so all three stay at or below 40 hours, redistributing the extra 6 total hours to part-time staff or adjusting shift start/end times' },
      { label: 'C', text: 'Tell the staff to clock out at 40 hours even if they are still working' },
      { label: 'D', text: 'Cancel Friday operations' },
    ],
    correctAnswer: 'B',
    explanation: "2 hours of overtime per employee at 1.5x rate costs significantly more than redistributing those hours. The system's labor cost projection should flag this before the schedule is published.",
  },
  {
    id: 'M18-Q05',
    moduleId: 'M18',
    questionText: "When should next week's schedule be drafted and published?",
    choices: [
      { label: 'A', text: 'Monday morning of that week' },
      { label: 'B', text: 'Draft by Wednesday, publish by Thursday noon' },
      { label: 'C', text: 'The first of the month for the whole month' },
      { label: 'D', text: 'Whenever there is time' },
    ],
    correctAnswer: 'B',
    explanation: 'Wednesday drafting allows time to check ratios and resolve conflicts. Thursday noon publication gives staff 2+ days to see their schedule and raise concerns before the week starts.',
  },
  {
    id: 'M18-Q06',
    moduleId: 'M18',
    questionText: 'The system shows a ratio compliance warning for Tuesday between 2:00 and 3:00 PM. What does this likely mean?',
    choices: [
      { label: 'A', text: 'Too many staff are scheduled' },
      { label: 'B', text: 'A gap exists where scheduled staff do not cover the projected child count for that hour' },
      { label: 'C', text: 'The system has a glitch' },
      { label: 'D', text: "A child has a doctor's appointment" },
    ],
    correctAnswer: 'B',
    explanation: 'The ratio compliance view cross-references scheduled staff hours with expected attendance patterns. A warning during that window means the projected child count exceeds what scheduled staff can cover.',
  },
  {
    id: 'M18-Q07',
    moduleId: 'M18',
    questionText: 'A center spends $340,000 annually on labor. If optimized scheduling reduces overtime by 15%, how much is saved?',
    choices: [
      { label: 'A', text: '$5,100' },
      { label: 'B', text: '$10,200' },
      { label: 'C', text: '$25,500' },
      { label: 'D', text: '$51,000' },
    ],
    correctAnswer: 'A',
    explanation: 'If overtime represents roughly 10% of labor ($34,000), a 15% reduction saves approximately $5,100. However, eliminating unnecessary full-time hours through staggered scheduling can yield even larger savings.',
  },
  {
    id: 'M18-Q08',
    moduleId: 'M18',
    questionText: 'Two staff members request the same day off and only one can be approved. How should you decide?',
    choices: [
      { label: 'A', text: 'Approve whoever asked first' },
      { label: 'B', text: 'Check who has more seniority' },
      { label: 'C', text: "Evaluate both requests against coverage needs, then apply the center's time-off policy (typically first-come basis, with seniority as tiebreaker)" },
      { label: 'D', text: 'Deny both' },
    ],
    correctAnswer: 'C',
    explanation: "The decision should follow the center's documented time-off policy. The system logs request timestamps to establish first-come priority. Whatever the decision, document the reasoning.",
  },
  {
    id: 'M18-Q09',
    moduleId: 'M18',
    questionText: 'A staff member consistently clocks in 10-15 minutes late. The schedule shows their shift starting at 7:00 AM, but they arrive at 7:10-7:15 AM. What is the scheduling impact?',
    choices: [
      { label: 'A', text: 'No impact; 15 minutes does not matter' },
      { label: 'B', text: 'The opening staff member is alone with more children than their ratio allows for those 10-15 minutes, creating a daily compliance gap' },
      { label: 'C', text: 'It only matters for payroll' },
      { label: 'D', text: 'The system automatically adjusts' },
    ],
    correctAnswer: 'B',
    explanation: 'Late arrivals at shift transitions are one of the most common causes of brief ratio violations. If the 7:00 AM staff member is needed to bring the room into ratio at 7:00, every late arrival is a violation.',
  },
  {
    id: 'M18-Q10',
    moduleId: 'M18',
    questionText: 'The owner wants to reduce labor costs by $20,000 next year without reducing staff. What scheduling strategy would you recommend?',
    choices: [
      { label: 'A', text: 'Cut all staff to part-time' },
      { label: 'B', text: 'Analyze attendance patterns to align staffing with actual child counts throughout the day, eliminating overlap hours where ratios are already met' },
      { label: 'C', text: 'Stop paying overtime entirely' },
      { label: 'D', text: 'Reduce operating hours by 2 hours per day' },
    ],
    correctAnswer: 'B',
    explanation: 'Data-driven scheduling matches staff hours to when children are actually present. Most centers have 2-3 hours per day where staffing exceeds ratio requirements by 1-2 people. Reducing those overlaps by even 1 hour per day across 5 staff saves approximately $20,000 annually.',
  },

  // ============================================================
  // M19: HR & Document Management (5 Questions)
  // ============================================================
  {
    id: 'M19-Q01',
    moduleId: 'M19',
    questionText: 'A staff member receives a verbal warning for repeated tardiness. Where should this be documented?',
    choices: [
      { label: 'A', text: 'In a personal notebook' },
      { label: 'B', text: "In the HR module under the staff member's discipline record" },
      { label: 'C', text: 'In a text message to the director' },
      { label: 'D', text: 'Nowhere; verbal warnings are just conversations' },
    ],
    correctAnswer: 'B',
    explanation: 'All disciplinary actions, including verbal warnings, must be documented in the HR system. Undocumented warnings have no legal standing if termination becomes necessary.',
  },
  {
    id: 'M19-Q02',
    moduleId: 'M19',
    questionText: 'A former employee files an unemployment claim and disputes their termination. The center has no written documentation of performance issues. What is the likely outcome?',
    choices: [
      { label: 'A', text: 'The center will win the claim easily' },
      { label: 'B', text: 'The center will likely pay the unemployment claim because there is no documentation to support the termination decision' },
      { label: 'C', text: 'It does not matter; unemployment claims are automatic' },
      { label: 'D', text: 'The employee must prove they were a good worker' },
    ],
    correctAnswer: 'B',
    explanation: 'Without documentation, the center cannot demonstrate cause for termination. Unemployment claims without supporting documentation typically favor the employee, costing the center increased unemployment insurance rates.',
  },
  {
    id: 'M19-Q03',
    moduleId: 'M19',
    questionText: "Which HR documents should be created using the system's templates rather than written freeform?",
    choices: [
      { label: 'A', text: 'Only termination letters' },
      { label: 'B', text: 'All HR actions: warnings, performance reviews, improvement plans, commendations, and termination documentation' },
      { label: 'C', text: 'Only documents that go to attorneys' },
      { label: 'D', text: 'None; freeform is better' },
    ],
    correctAnswer: 'B',
    explanation: 'Templates ensure consistency, completeness, and legal compliance. Freeform documents often miss required elements that become problems during disputes.',
  },
  {
    id: 'M19-Q04',
    moduleId: 'M19',
    questionText: 'How long should employee HR records be retained after the employee leaves?',
    choices: [
      { label: 'A', text: '30 days' },
      { label: 'B', text: '1 year' },
      { label: 'C', text: 'A minimum of 3 years (Minnesota requirement; some records up to 7 years)' },
      { label: 'D', text: 'They should be deleted immediately' },
    ],
    correctAnswer: 'C',
    explanation: 'Minnesota requires retention of employment records for a minimum of 3 years. Payroll records must be kept longer. The digital system makes retention automatic, but the policy must be understood.',
  },
  {
    id: 'M19-Q05',
    moduleId: 'M19',
    questionText: 'A staff member asks to see their own HR file. What is the correct response?',
    choices: [
      { label: 'A', text: 'Deny the request; HR files are confidential' },
      { label: 'B', text: 'Under Minnesota law, employees have the right to review their personnel file; schedule a time for them to review it' },
      { label: 'C', text: 'Give them a copy immediately with no restrictions' },
      { label: 'D', text: 'Tell them to hire a lawyer' },
    ],
    correctAnswer: 'B',
    explanation: 'Minnesota Statute 181.961 gives employees the right to review their personnel file. The center must provide access within 7 working days of a written request.',
  },

  // ============================================================
  // M20: Payroll Management (5 Questions)
  // ============================================================
  {
    id: 'M20-Q01',
    moduleId: 'M20',
    questionText: 'You are reviewing time entries for the week and notice a staff member logged 10.5 hours on Tuesday but their scheduled shift was 8 hours. What should you do?',
    choices: [
      { label: 'A', text: 'Approve it without question' },
      { label: 'B', text: 'Compare the time entry against the schedule, check if overtime was authorized, and verify with the staff member before approving' },
      { label: 'C', text: 'Automatically reduce it to 8 hours' },
      { label: 'D', text: 'Ignore it; payroll will sort it out' },
    ],
    correctAnswer: 'B',
    explanation: 'Discrepancies between scheduled and actual hours require investigation before approval. The extra 2.5 hours could be legitimate (stayed for coverage) or an error (forgot to clock out).',
  },
  {
    id: 'M20-Q02',
    moduleId: 'M20',
    questionText: 'A staff member worked 44 hours this week. Their regular rate is $16/hour. What is their gross pay?',
    choices: [
      { label: 'A', text: '$704.00' },
      { label: 'B', text: '$736.00' },
      { label: 'C', text: '$720.00' },
      { label: 'D', text: '$680.00' },
    ],
    correctAnswer: 'B',
    explanation: '40 hours at $16 = $640, plus 4 overtime hours at $24 (1.5x) = $96. Total: $736.00. The system should flag the overtime before the payroll period closes.',
  },
  {
    id: 'M20-Q03',
    moduleId: 'M20',
    questionText: 'When should time entries be reviewed each week?',
    choices: [
      { label: 'A', text: 'At the end of the month' },
      { label: 'B', text: 'Every Friday, before the payroll period closes' },
      { label: 'C', text: 'Only when an employee complains' },
      { label: 'D', text: 'Every day' },
    ],
    correctAnswer: 'B',
    explanation: 'Friday review catches errors, unauthorized overtime, and missed clock-ins/outs before the pay period closes. This prevents payroll corrections and reissued checks.',
  },
  {
    id: 'M20-Q04',
    moduleId: 'M20',
    questionText: 'A staff member forgot to clock in on Monday. They say they arrived at 7:00 AM as scheduled. What is the process?',
    choices: [
      { label: 'A', text: 'Take their word and add the time' },
      { label: 'B', text: 'Verify with the opening staff or kiosk check-in records, then add a manual entry with a note explaining the correction' },
      { label: 'C', text: 'Do not pay them for Monday' },
      { label: 'D', text: 'Round their time to the nearest hour' },
    ],
    correctAnswer: 'B',
    explanation: 'Manual time entries require verification and documentation. The note in the system creates an audit trail showing the correction was investigated, not just rubber-stamped.',
  },
  {
    id: 'M20-Q05',
    moduleId: 'M20',
    questionText: 'Catching time entry errors saves an estimated 2-5% of labor costs. For a center spending $340,000 on labor annually, what is the potential savings range?',
    choices: [
      { label: 'A', text: '$1,700 to $3,400' },
      { label: 'B', text: '$3,400 to $8,500' },
      { label: 'C', text: '$6,800 to $17,000' },
      { label: 'D', text: '$17,000 to $34,000' },
    ],
    correctAnswer: 'C',
    explanation: '2% of $340,000 = $6,800; 5% = $17,000. These savings come from catching buddy punching, rounding errors, forgotten clock-outs, and unauthorized overtime.',
  },

  // ============================================================
  // M21: Staff Onboarding (5 Questions)
  // ============================================================
  {
    id: 'M21-Q01',
    moduleId: 'M21',
    questionText: 'A new hire starts Monday. When should their digital onboarding pathway be created?',
    choices: [
      { label: 'A', text: 'Monday morning when they arrive' },
      { label: 'B', text: 'Before their first day, ideally when the offer is accepted' },
      { label: 'C', text: 'After their first week' },
      { label: 'D', text: 'Only if they ask for it' },
    ],
    correctAnswer: 'B',
    explanation: 'Pre-day-1 onboarding setup means the new hire walks in to a structured plan rather than improvisation. The system can send welcome materials and initial tasks before they arrive.',
  },
  {
    id: 'M21-Q02',
    moduleId: 'M21',
    questionText: 'Which compliance items must be completed before a new hire can be alone in a room with children?',
    choices: [
      { label: 'A', text: 'Just a background check' },
      { label: 'B', text: 'Background check cleared, CPR/First Aid certification current, mandatory reporter training complete, center orientation finished' },
      { label: 'C', text: 'Only their signed employment agreement' },
      { label: 'D', text: 'Nothing; they can start immediately' },
    ],
    correctAnswer: 'B',
    explanation: 'Minnesota requires all four elements before a staff member can be counted in ratios. The onboarding checklist tracks completion so no one falls through the cracks.',
  },
  {
    id: 'M21-Q03',
    moduleId: 'M21',
    questionText: 'The average cost to replace a child care staff member is:',
    choices: [
      { label: 'A', text: '$500-1,000' },
      { label: 'B', text: '$1,000-2,000' },
      { label: 'C', text: '$3,000-5,000' },
      { label: 'D', text: '$10,000-15,000' },
    ],
    correctAnswer: 'C',
    explanation: 'Replacement costs include recruiting, background checks, training time, reduced productivity during learning curve, and potential overtime to cover gaps. Structured onboarding reduces turnover by 25%.',
  },
  {
    id: 'M21-Q04',
    moduleId: 'M21',
    questionText: "At which checkpoints should a new hire's onboarding progress be reviewed?",
    choices: [
      { label: 'A', text: 'Only at 90 days' },
      { label: 'B', text: 'Day 1, end of week 1, and end of month 1' },
      { label: 'C', text: 'Whenever the director remembers' },
      { label: 'D', text: 'Only if the new hire asks questions' },
    ],
    correctAnswer: 'B',
    explanation: 'Three checkpoints catch issues early. Day 1 confirms basics are in place. Week 1 identifies confusion or gaps. Month 1 assesses whether the hire is on track toward independence.',
  },
  {
    id: 'M21-Q05',
    moduleId: 'M21',
    questionText: 'A new employee completes all onboarding checklist items in 3 days. Does this mean onboarding is finished?',
    choices: [
      { label: 'A', text: 'Yes, they are fully onboarded' },
      { label: 'B', text: 'No. Checklist completion is the compliance baseline. Full onboarding includes supervised practice, competency assessment, and mentorship over the first 30 days' },
      { label: 'C', text: 'Yes, as long as the director signs off' },
      { label: 'D', text: 'They should redo the checklist to be thorough' },
    ],
    correctAnswer: 'B',
    explanation: 'The checklist ensures compliance requirements are met. Actual competency, built through supervised practice and feedback, takes weeks. The competency rubric tracks progress toward independent performance.',
  },

  // ============================================================
  // M22: Enrollment Pipeline (10 Questions)
  // ============================================================
  {
    id: 'M22-Q01',
    moduleId: 'M22',
    questionText: 'A parent calls asking about availability for their 2-year-old. What is the first action in the system?',
    choices: [
      { label: 'A', text: 'Tell them to check the website' },
      { label: 'B', text: "Create a new inquiry in the enrollment pipeline with the child's age, parent name, contact info, and date of inquiry" },
      { label: 'C', text: 'Add the child directly to a classroom roster' },
      { label: 'D', text: 'Wait to see if they call back' },
    ],
    correctAnswer: 'B',
    explanation: 'Every inquiry gets logged immediately. Unlogged inquiries are lost revenue. The pipeline tracks the prospect from first contact through enrollment.',
  },
  {
    id: 'M22-Q02',
    moduleId: 'M22',
    questionText: 'The enrollment pipeline shows 8 inquiries, 3 tours scheduled, and 1 enrolled in the past month. What is the tour-to-enrollment conversion rate?',
    choices: [
      { label: 'A', text: '12.5%' },
      { label: 'B', text: '33%' },
      { label: 'C', text: '37.5%' },
      { label: 'D', text: '100%' },
    ],
    correctAnswer: 'B',
    explanation: ' 1 enrolled out of 3 tours = 33% conversion. Industry average is around 50%, so this rate suggests room to improve the tour experience or follow-up process.',
  },
  {
    id: 'M22-Q03',
    moduleId: 'M22',
    questionText: 'A prospective family toured 5 days ago and you have not heard back. What should you do?',
    choices: [
      { label: 'A', text: 'Assume they are not interested' },
      { label: 'B', text: 'Check the pipeline for their follow-up date; if past 48 hours, send a personalized follow-up message' },
      { label: 'C', text: 'Call them every day until they respond' },
      { label: 'D', text: 'Remove them from the pipeline' },
    ],
    correctAnswer: 'B',
    explanation: 'The 48-hour follow-up window is the standard. Leads that go uncontacted beyond 48 hours after a tour drop significantly in conversion probability.',
  },
  {
    id: 'M22-Q04',
    moduleId: 'M22',
    questionText: 'Each enrolled child generates approximately how much monthly revenue?',
    choices: [
      { label: 'A', text: '$200-400' },
      { label: 'B', text: '$400-600' },
      { label: 'C', text: '$800-1,200' },
      { label: 'D', text: '$2,000-3,000' },
    ],
    correctAnswer: 'C',
    explanation: 'With tuition averaging $800-1,200/month depending on age and schedule, each enrolled child represents significant recurring revenue. This is why pipeline management matters.',
  },
  {
    id: 'M22-Q05',
    moduleId: 'M22',
    questionText: 'The pipeline shows 4 inquiries have been "stalled" for over 2 weeks with no follow-up logged. What is the business impact?',
    choices: [
      { label: 'A', text: 'No impact; they will call back if interested' },
      { label: 'B', text: 'At $1,000/month average revenue per child, those 4 stalled leads represent up to $48,000 in potential annual revenue that may be lost to competitors' },
      { label: 'C', text: 'It only matters at the end of the year' },
      { label: 'D', text: 'Stalled leads always come back' },
    ],
    correctAnswer: 'B',
    explanation: '4 children x $1,000/month x 12 months = $48,000. Even converting 2 of the 4 recovers $24,000 annually. Stalled pipelines are the most common enrollment revenue leak.',
  },
  {
    id: 'M22-Q06',
    moduleId: 'M22',
    questionText: 'What information should be captured during the initial inquiry call?',
    choices: [
      { label: 'A', text: "Just the parent's name" },
      { label: 'B', text: 'Parent name, phone, email, child\'s name, age/birthdate, desired start date, how they heard about the center, schedule preference' },
      { label: 'C', text: 'Only whether they want a tour' },
      { label: 'D', text: 'Their social security number' },
    ],
    correctAnswer: 'B',
    explanation: 'Complete intake data enables personalized follow-up, accurate capacity planning, and marketing effectiveness tracking ("how did you hear about us" data).',
  },
  {
    id: 'M22-Q07',
    moduleId: 'M22',
    questionText: 'A family completed all enrollment paperwork but has not brought their child for the first day, and it has been 2 weeks past the agreed start date. What should you do?',
    choices: [
      { label: 'A', text: 'Remove them from the roster' },
      { label: 'B', text: 'Contact the family to confirm their plans, document the conversation, and determine whether to hold the spot or release it to the waitlist' },
      { label: 'C', text: 'Keep the spot indefinitely' },
      { label: 'D', text: 'Charge them for the 2 weeks' },
    ],
    correctAnswer: 'B',
    explanation: 'Unrealized enrollments occupy capacity that could serve waitlisted families. A defined policy (e.g., spot held for 5 business days past start date) should be applied consistently.',
  },
  {
    id: 'M22-Q08',
    moduleId: 'M22',
    questionText: "The waitlist for the infant room has 6 families. Current infant enrollment is at capacity (8 children, 2 staff). A family gives 2 weeks' notice that they are leaving. What is the process?",
    choices: [
      { label: 'A', text: 'Wait for the family to leave, then figure it out' },
      { label: 'B', text: "Contact the first waitlist family immediately to offer the spot with a target start date aligned to the departing family's last day" },
      { label: 'C', text: 'Post the opening on social media' },
      { label: 'D', text: 'Eliminate the waitlist' },
    ],
    correctAnswer: 'B',
    explanation: 'Timing the transition minimizes vacancy days. Each day an infant spot sits empty costs approximately $40-55 in lost revenue. Contacting the waitlist family 2 weeks early gives them time to prepare.',
  },
  {
    id: 'M22-Q09',
    moduleId: 'M22',
    questionText: 'A tour is scheduled for tomorrow at 10:00 AM. What should you do today?',
    choices: [
      { label: 'A', text: 'Nothing; just be ready tomorrow' },
      { label: 'B', text: 'Send a confirmation message to the family, verify the tour route is presentable, prepare an enrollment packet, and brief the classroom staff' },
      { label: 'C', text: 'Cancel the tour if it is inconvenient' },
      { label: 'D', text: 'Have the parent just show up whenever' },
    ],
    correctAnswer: 'B',
    explanation: 'Tour preparation increases conversion rates. Confirmation reduces no-shows. A prepared, professional tour experience differentiates the center from competitors.',
  },
  {
    id: 'M22-Q10',
    moduleId: 'M22',
    questionText: 'The enrollment dashboard shows that 60% of inquiries come from the center\'s website, 25% from referrals, and 15% from social media. How should this inform marketing decisions?',
    choices: [
      { label: 'A', text: 'Spend more on TV advertising' },
      { label: 'B', text: 'Invest most marketing effort in website optimization and referral programs since they drive 85% of inquiries, while maintaining but not increasing social media' },
      { label: 'C', text: 'Stop all marketing; inquiries are coming in already' },
      { label: 'D', text: 'Only invest in social media since it is trendy' },
    ],
    correctAnswer: 'B',
    explanation: 'Data-driven marketing allocates budget to channels that produce results. Strengthening the top 2 channels (website + referrals) while maintaining the third is efficient resource allocation.',
  },

  // ============================================================
  // M24: Authorization Tracking (5 Questions)
  // ============================================================
  {
    id: 'M24-Q01',
    moduleId: 'M24',
    questionText: "A child's county authorization expires in 14 days. What should happen?",
    choices: [
      { label: 'A', text: 'Wait until it expires to start the renewal' },
      { label: 'B', text: 'Contact the family immediately to begin the renewal process; the 14-day alert means action is overdue since the 60-day and 30-day alerts were missed or unresolved' },
      { label: 'C', text: 'Remove the child from the roster' },
      { label: 'D', text: 'Nothing; the county will renew it automatically' },
    ],
    correctAnswer: 'B',
    explanation: "By 14 days out, renewal should already be in progress. If the family has not initiated renewal, direct outreach is critical. A lapsed authorization means the center cannot bill for that child's care.",
  },
  {
    id: 'M24-Q02',
    moduleId: 'M24',
    questionText: "A child's authorization lapses on Monday. The child shows up Tuesday morning. What should the director do?",
    choices: [
      { label: 'A', text: 'Accept the child as normal; the paperwork will catch up' },
      { label: 'B', text: "Check the center's policy: the child may attend, but the center cannot bill for unauthorized days, creating unbillable revenue loss until authorization is restored" },
      { label: 'C', text: 'Send the child home' },
      { label: 'D', text: 'Call the police' },
    ],
    correctAnswer: 'B',
    explanation: 'Policies vary, but the financial reality is consistent: unauthorized days generate no reimbursement. Some centers allow attendance to maintain the family relationship while aggressively pursuing reauthorization. Others require active authorization for attendance.',
  },
  {
    id: 'M24-Q03',
    moduleId: 'M24',
    questionText: 'The authorization dashboard shows "revenue at risk" of $4,200. What does this number represent?',
    choices: [
      { label: 'A', text: "The center's total monthly revenue" },
      { label: 'B', text: 'The projected lost revenue if all currently expiring authorizations lapse without renewal' },
      { label: 'C', text: 'The amount owed to the state' },
      { label: 'D', text: 'The cost of processing renewals' },
    ],
    correctAnswer: 'B',
    explanation: 'Revenue-at-risk calculates the monthly tuition/reimbursement for all children whose authorizations are approaching expiration. It quantifies the urgency of renewal follow-up.',
  },
  {
    id: 'M24-Q04',
    moduleId: 'M24',
    questionText: 'What is the recommended point to begin the authorization renewal process?',
    choices: [
      { label: 'A', text: '7 days before expiration' },
      { label: 'B', text: '60 days before expiration' },
      { label: 'C', text: 'After it expires' },
      { label: 'D', text: '90 days before expiration' },
    ],
    correctAnswer: 'B',
    explanation: 'The 60-day alert is the action trigger. Starting at 60 days provides enough time for family response, county processing, and any documentation requirements.',
  },
  {
    id: 'M24-Q05',
    moduleId: 'M24',
    questionText: 'A family says, "The county told us our renewal is processing." The authorization expires in 5 days. What should you do?',
    choices: [
      { label: 'A', text: 'Accept their word and stop following up' },
      { label: 'B', text: "Document the family's statement, request a reference number or processing confirmation, and set a daily follow-up until the renewed authorization appears in the system" },
      { label: 'C', text: 'Call the county yourself and demand faster processing' },
      { label: 'D', text: 'Disenroll the child' },
    ],
    correctAnswer: 'B',
    explanation: "Trust but verify. Documenting the family's statement protects both parties. Daily follow-up near expiration ensures the center knows the moment authorization is confirmed or lapses.",
  },

  // ============================================================
  // M26: Budget Planning & Tracking (10 Questions)
  // ============================================================
  {
    id: 'M26-Q01',
    moduleId: 'M26',
    questionText: 'When reviewing monthly budget versus actuals, what variance threshold should trigger investigation?',
    choices: [
      { label: 'A', text: 'Any variance at all' },
      { label: 'B', text: 'Greater than 10% over budget in any category' },
      { label: 'C', text: 'Greater than 50% over budget' },
      { label: 'D', text: 'Only if total spending exceeds the annual budget' },
    ],
    correctAnswer: 'B',
    explanation: 'A 10% threshold balances responsiveness with practicality. Smaller variances are normal fluctuations. Larger than 10% indicates a trend or error that needs attention.',
  },
  {
    id: 'M26-Q02',
    moduleId: 'M26',
    questionText: 'The center budgeted $28,000 for supplies this year. After 6 months, $19,000 has been spent. What does this indicate?',
    choices: [
      { label: 'A', text: 'Everything is fine; we are only at 67% of budget' },
      { label: 'B', text: 'At the current rate, the center will spend $38,000 by year end, exceeding the budget by $10,000. Investigation and adjustment are needed now.' },
      { label: 'C', text: 'We should spend more in the second half to use the budget' },
      { label: 'D', text: 'Supplies do not matter for budget tracking' },
    ],
    correctAnswer: 'B',
    explanation: '$19,000 in 6 months projects to $38,000 annually, a 36% overage. Catching this at the midpoint allows course correction (bulk purchasing, vendor renegotiation, consumption audit).',
  },
  {
    id: 'M26-Q03',
    moduleId: 'M26',
    questionText: "Which expense category typically represents the largest portion of a child care center's budget?",
    choices: [
      { label: 'A', text: 'Supplies and materials' },
      { label: 'B', text: 'Rent/mortgage' },
      { label: 'C', text: 'Labor (wages and benefits)' },
      { label: 'D', text: 'Food' },
    ],
    correctAnswer: 'C',
    explanation: 'Labor is typically 56% of total expenses. This is why scheduling optimization and overtime management are the highest-impact financial controls.',
  },
  {
    id: 'M26-Q04',
    moduleId: 'M26',
    questionText: 'The budget dashboard shows revenue of $42,000 and expenses of $44,500 for the month. What is the operating margin?',
    choices: [
      { label: 'A', text: '+$2,500' },
      { label: 'B', text: '-$2,500' },
      { label: 'C', text: '+5.6%' },
      { label: 'D', text: '-5.6%' },
    ],
    correctAnswer: 'B',
    explanation: 'Revenue minus expenses: $42,000 - $44,500 = -$2,500. The center lost $2,500 this month. If this is a trend rather than a one-month anomaly, structural changes (revenue increases or expense reductions) are needed.',
  },
  {
    id: 'M26-Q05',
    moduleId: 'M26',
    questionText: 'When should the annual budget be reviewed against actuals?',
    choices: [
      { label: 'A', text: 'At the end of the year' },
      { label: 'B', text: 'On the 1st of every month' },
      { label: 'C', text: 'Only when cash flow feels tight' },
      { label: 'D', text: 'Quarterly' },
    ],
    correctAnswer: 'B',
    explanation: 'Monthly review catches trends before they become crises. Quarterly review is too infrequent; by the time a quarterly report shows a problem, 3 months of overspending have already occurred.',
  },
  {
    id: 'M26-Q06',
    moduleId: 'M26',
    questionText: 'A line item for "professional development" shows $0 budgeted and $0 spent. What concern should this raise?',
    choices: [
      { label: 'A', text: 'None; saving money is good' },
      { label: 'B', text: 'Minnesota requires 16 hours of annual training per staff member, so $0 budgeted for PD may indicate a compliance gap or that training costs are hidden in other categories' },
      { label: 'C', text: 'Professional development is optional' },
      { label: 'D', text: 'The system must be broken' },
    ],
    correctAnswer: 'B',
    explanation: 'Zero-budgeted mandatory expenses suggest either misclassification (training costs hidden in "general" or "miscellaneous") or failure to plan for a compliance requirement.',
  },
  {
    id: 'M26-Q07',
    moduleId: 'M26',
    questionText: 'The center operates two sites. Brooklyn Park shows a 12% labor cost overage; Crystal shows 3% under budget. What should the owner investigate?',
    choices: [
      { label: 'A', text: 'Nothing; they average out to acceptable' },
      { label: 'B', text: "Why Brooklyn Park is 12% over: check overtime, staffing levels versus enrollment, and scheduling efficiency. Crystal's performance may reveal practices to replicate." },
      { label: 'C', text: "Cut Crystal's budget since they are under" },
      { label: 'D', text: 'Move all children to Crystal' },
    ],
    correctAnswer: 'B',
    explanation: "Site-level variance analysis identifies where specific operational issues exist. Averaging across sites hides problems. Brooklyn Park's overage could be unauthorized overtime, overstaffing relative to enrollment, or scheduling inefficiency.",
  },
  {
    id: 'M26-Q08',
    moduleId: 'M26',
    questionText: 'What is the purpose of the budget export to Excel function?',
    choices: [
      { label: 'A', text: 'To create pretty spreadsheets' },
      { label: 'B', text: 'To share financial data with the accountant, tax preparer, or board of directors in a format they can analyze independently' },
      { label: 'C', text: 'To replace the system entirely' },
      { label: 'D', text: 'To delete budget data' },
    ],
    correctAnswer: 'B',
    explanation: 'External stakeholders (accountants, board members) often need financial data in spreadsheet format for their own analysis, tax preparation, or reporting requirements.',
  },
  {
    id: 'M26-Q09',
    moduleId: 'M26',
    questionText: "The center receives $72,000 in annual CACFP reimbursement. If the budget does not account for CACFP as a revenue line and only tracks tuition, what is the risk?",
    choices: [
      { label: 'A', text: 'No risk; CACFP is a bonus' },
      { label: 'B', text: 'The budget understates total revenue by $72,000, which distorts margin calculations, makes the center appear less financially healthy than it is, and removes incentive to protect CACFP compliance' },
      { label: 'C', text: 'CACFP should not be in the budget' },
      { label: 'D', text: 'The center must return the CACFP money' },
    ],
    correctAnswer: 'B',
    explanation: 'CACFP reimbursement is earned revenue that must be budgeted, tracked, and protected. Excluding it from the budget means the owner cannot see the true financial picture or quantify the cost of compliance failures.',
  },
  {
    id: 'M26-Q10',
    moduleId: 'M26',
    questionText: 'A new playground structure costs $15,000. The budget has $5,000 remaining in the "facility improvements" category. What is the correct approach?',
    choices: [
      { label: 'A', text: 'Buy it anyway and worry about the budget later' },
      { label: 'B', text: 'Evaluate options: defer to next budget year, reallocate from underspent categories (if policy allows), seek a grant, or finance the purchase with a documented payment plan' },
      { label: 'C', text: 'Cut staff hours to fund it' },
      { label: 'D', text: 'Ask parents to donate' },
    ],
    correctAnswer: 'B',
    explanation: 'Capital expenses exceeding budget require deliberate decision-making. The system provides visibility into other categories that may have room, but reallocation should follow documented policy.',
  },

  // ============================================================
  // M27: Revenue Forecasting (10 Questions)
  // ============================================================
  {
    id: 'M27-Q01',
    moduleId: 'M27',
    questionText: 'The center currently has 38 children enrolled with average monthly revenue of $1,050 per child. What is the projected monthly revenue?',
    choices: [
      { label: 'A', text: '$38,000' },
      { label: 'B', text: '$39,900' },
      { label: 'C', text: '$42,000' },
      { label: 'D', text: '$45,000' },
    ],
    correctAnswer: 'B',
    explanation: '38 x $1,050 = $39,900. This is the baseline for forecasting, before adjustments for expected enrollment changes, rate increases, or seasonal patterns.',
  },
  {
    id: 'M27-Q02',
    moduleId: 'M27',
    questionText: 'Enrollment typically drops by 3 children during summer when school-age kids go to camps. If those 3 children paid $900/month each, what is the summer revenue impact over June, July, and August?',
    choices: [
      { label: 'A', text: '$2,700' },
      { label: 'B', text: '$5,400' },
      { label: 'C', text: '$8,100' },
      { label: 'D', text: '$10,800' },
    ],
    correctAnswer: 'C',
    explanation: '3 children x $900 x 3 months = $8,100 in seasonal revenue loss. Forecasting this allows the owner to plan reduced staffing or summer-only enrollment to offset the dip.',
  },
  {
    id: 'M27-Q03',
    moduleId: 'M27',
    questionText: 'The owner considers raising tuition by $50/month across all 40 enrolled families. What is the annual revenue increase?',
    choices: [
      { label: 'A', text: '$2,000' },
      { label: 'B', text: '$12,000' },
      { label: 'C', text: '$24,000' },
      { label: 'D', text: '$36,000' },
    ],
    correctAnswer: 'C',
    explanation: '40 families x $50 x 12 months = $24,000. However, the forecast should also model potential enrollment loss from the rate increase to determine net impact.',
  },
  {
    id: 'M27-Q04',
    moduleId: 'M27',
    questionText: 'A "what-if" scenario shows that losing 5 children would reduce annual revenue by $63,000. The owner is considering a policy change that families have complained about. What should the forecast inform?',
    choices: [
      { label: 'A', text: 'Nothing; make the policy change anyway' },
      { label: 'B', text: 'The potential revenue loss should be weighed against the benefit of the policy change. If the change risks losing even 3-5 families, the $63,000 downside must be factored into the decision.' },
      { label: 'C', text: 'Cancel all policy changes forever' },
      { label: 'D', text: 'Raise tuition to offset potential losses' },
    ],
    correctAnswer: 'B',
    explanation: 'Scenario modeling quantifies the financial risk of operational decisions. Not every decision should be purely financial, but the owner should make decisions with full visibility into the cost.',
  },
  {
    id: 'M27-Q05',
    moduleId: 'M27',
    questionText: 'The P&L statement shows revenue of $500,000 and total expenses of $485,000 for the year. What is the profit margin?',
    choices: [
      { label: 'A', text: '3%' },
      { label: 'B', text: '5%' },
      { label: 'C', text: '10%' },
      { label: 'D', text: '15%' },
    ],
    correctAnswer: 'A',
    explanation: '($500,000 - $485,000) / $500,000 = 3%. Child care profit margins are typically thin (5-10%). At 3%, the center has very little buffer for unexpected expenses.',
  },
  {
    id: 'M27-Q06',
    moduleId: 'M27',
    questionText: 'The revenue forecast projects a cash shortfall in February. What proactive steps can the owner take?',
    choices: [
      { label: 'A', text: 'Wait until February and hope for the best' },
      { label: 'B', text: 'Identify the cause (seasonal enrollment dip, tuition collection lag, large expense due), then plan: accelerate enrollment pipeline activity, negotiate expense timing with vendors, or build a cash reserve in the months leading up' },
      { label: 'C', text: 'Close the center in February' },
      { label: 'D', text: "Borrow from next month's tuition" },
    ],
    correctAnswer: 'B',
    explanation: 'Forecasting exists to prevent surprises. A projected February shortfall visible in October gives 4 months to address it. Waiting until February turns a manageable issue into a crisis.',
  },
  {
    id: 'M27-Q07',
    moduleId: 'M27',
    questionText: "CACFP reimbursement is $6,000/month. If the center's audit readiness score drops and reimbursement is suspended for 2 months during investigation, what is the revenue impact?",
    choices: [
      { label: 'A', text: '$3,000' },
      { label: 'B', text: '$6,000' },
      { label: 'C', text: '$12,000' },
      { label: 'D', text: '$24,000' },
    ],
    correctAnswer: 'C',
    explanation: '$6,000 x 2 months = $12,000. This is pure revenue loss with no corresponding expense reduction, making it a direct hit to the bottom line.',
  },
  {
    id: 'M27-Q08',
    moduleId: 'M27',
    questionText: 'The owner runs a scenario: "What if I add 2 infant spots by converting a storage room?" Infant tuition is $1,400/month. What additional annual revenue would this generate?',
    choices: [
      { label: 'A', text: '$16,800' },
      { label: 'B', text: '$25,200' },
      { label: 'C', text: '$33,600' },
      { label: 'D', text: '$50,400' },
    ],
    correctAnswer: 'C',
    explanation: '2 infants x $1,400 x 12 months = $33,600. The forecast should also model the costs: additional staff (infant ratio 1:4 means you may need another staff member), room conversion costs, and licensing approval timeline.',
  },
  {
    id: 'M27-Q09',
    moduleId: 'M27',
    questionText: 'Which factor has the LARGEST impact on revenue forecasting accuracy?',
    choices: [
      { label: 'A', text: 'Supply costs' },
      { label: 'B', text: 'Enrollment stability (how many children stay versus leave)' },
      { label: 'C', text: 'Utility rates' },
      { label: 'D', text: 'Weather patterns' },
    ],
    correctAnswer: 'B',
    explanation: 'Enrollment is the primary revenue driver. A single child leaving represents $10,000-16,000 in annual revenue. Accurate retention forecasting depends on tracking disenrollment patterns and family satisfaction.',
  },
  {
    id: 'M27-Q10',
    moduleId: 'M27',
    questionText: 'The forecast shows the center breaking even at 35 enrolled children. Current enrollment is 38. What does this mean?',
    choices: [
      { label: 'A', text: 'The center can afford to lose up to 10 children' },
      { label: 'B', text: 'The center has a 3-child cushion before it starts losing money. Any enrollment drop below 35 requires immediate cost reduction or revenue recovery.' },
      { label: 'C', text: 'Everything is fine forever' },
      { label: 'D', text: 'The center should stop marketing' },
    ],
    correctAnswer: 'B',
    explanation: 'A 3-child cushion is thin. The owner should know the breakeven point and treat enrollment below 37 as a warning zone that triggers pipeline activation and retention focus.',
  },

  // ============================================================
  // M28: Cost Optimization (5 Questions)
  // ============================================================
  {
    id: 'M28-Q01',
    moduleId: 'M28',
    questionText: 'The expense breakdown shows food costs at 18% of total expenses while the industry average is 12%. What should the owner investigate?',
    choices: [
      { label: 'A', text: 'Nothing; children need to eat' },
      { label: 'B', text: 'Vendor pricing, portion waste, menu planning efficiency, and whether CACFP reimbursement is properly offsetting food costs' },
      { label: 'C', text: 'Serve less food' },
      { label: 'D', text: 'Switch to the cheapest possible food' },
    ],
    correctAnswer: 'B',
    explanation: 'A 6-percentage-point gap above industry average signals inefficiency, not generosity. Common causes: overordering, waste, premium vendor pricing without comparison shopping, or CACFP reimbursement not being applied against food line items.',
  },
  {
    id: 'M28-Q02',
    moduleId: 'M28',
    questionText: 'Labor is 62% of total expenses (industry target: 56%). The center spends $340,000 on labor. What dollar amount represents the gap?',
    choices: [
      { label: 'A', text: '$6,000' },
      { label: 'B', text: '$12,000' },
      { label: 'C', text: '$24,000' },
      { label: 'D', text: '$36,000' },
    ],
    correctAnswer: 'D',
    explanation: 'If total expenses are $340,000 / 0.62 = $548,387, then 56% of that = $307,097. The gap is $340,000 - $307,097 = approximately $33,000 to $36,000, depending on rounding. This is the optimization target.',
  },
  {
    id: 'M28-Q03',
    moduleId: 'M28',
    questionText: 'The owner identifies that 2 staff members overlap for 2 hours each day in the preschool room when ratios only require 1 during that window. If the overlap rate is $16/hour, what is the weekly cost of unnecessary overlap?',
    choices: [
      { label: 'A', text: '$32' },
      { label: 'B', text: '$160' },
      { label: 'C', text: '$320' },
      { label: 'D', text: '$640' },
    ],
    correctAnswer: 'B',
    explanation: '2 hours x $16 x 5 days = $160/week. Over a year: $160 x 50 weeks = $8,000 in potentially unnecessary labor expense.',
  },
  {
    id: 'M28-Q04',
    moduleId: 'M28',
    questionText: 'The center can maximize CACFP reimbursement by ensuring all eligible meals are counted and submitted on time. Current capture rate is 85%. If full capture (100%) would generate $84,000 annually, how much is the center leaving on the table?',
    choices: [
      { label: 'A', text: '$6,300' },
      { label: 'B', text: '$8,400' },
      { label: 'C', text: '$12,600' },
      { label: 'D', text: '$16,800' },
    ],
    correctAnswer: 'C',
    explanation: '$84,000 x 15% missed = $12,600 in unrealized CACFP revenue. This is money already available to the center; it just requires consistent, timely meal count submission.',
  },
  {
    id: 'M28-Q05',
    moduleId: 'M28',
    questionText: 'An owner says, "I don\'t have time to review expenses every month." What is the risk?',
    choices: [
      { label: 'A', text: 'No risk; the accountant handles it' },
      { label: 'B', text: 'Expenses drift without accountability. Small overages compound. A 5% monthly drift unnoticed for 6 months can cost $15,000-20,000 before anyone realizes it.' },
      { label: 'C', text: 'The budget balances itself' },
      { label: 'D', text: 'Monthly review is overkill' },
    ],
    correctAnswer: 'B',
    explanation: 'Monthly review takes 30-60 minutes with the budget dashboard. The cost of skipping it (undetected overages, missed optimization opportunities) far exceeds the time investment.',
  },

  // ============================================================
  // M30: Strategic Planning (5 Questions)
  // ============================================================
  {
    id: 'M30-Q01',
    moduleId: 'M30',
    questionText: 'The center has documented mission, vision, and values. How often should these be reviewed?',
    choices: [
      { label: 'A', text: 'Never; once written, they are permanent' },
      { label: 'B', text: 'Annually, with a full refresh of the strategic plan' },
      { label: 'C', text: 'Only when there is a crisis' },
      { label: 'D', text: 'Every week' },
    ],
    correctAnswer: 'B',
    explanation: 'Annual review ensures alignment with current reality. Markets, regulations, and family needs change. A mission statement written 5 years ago may not reflect current priorities.',
  },
  {
    id: 'M30-Q02',
    moduleId: 'M30',
    questionText: 'During a SWOT analysis, the owner identifies "high staff turnover" as a weakness. Which of the following is a strategic response?',
    choices: [
      { label: 'A', text: 'Ignore it; turnover is normal in child care' },
      { label: 'B', text: 'Set a measurable retention goal (e.g., reduce annual turnover from 40% to 25%), identify root causes using exit interviews and HR data, and implement specific changes (compensation review, structured onboarding, career pathways)' },
      { label: 'C', text: 'Hire temporary staff to fill gaps' },
      { label: 'D', text: 'Blame the labor market' },
    ],
    correctAnswer: 'B',
    explanation: 'Strategic response means measurable goal, root cause analysis, and specific actions with timelines. Vague responses ("we\'ll try to keep people longer") are not strategy.',
  },
  {
    id: 'M30-Q03',
    moduleId: 'M30',
    questionText: 'The strategic plan includes 5 priorities. After 3 months, the owner has made progress on 1 and has not started the other 4. What does this indicate?',
    choices: [
      { label: 'A', text: 'The plan is working fine' },
      { label: 'B', text: 'The plan may have too many priorities, insufficient accountability structures, or competing operational demands that prevent strategic work. The owner should reassess: narrow to 2-3 priorities and create specific weekly actions.' },
      { label: 'C', text: 'Strategic plans are aspirational; completion does not matter' },
      { label: 'D', text: 'Add 5 more priorities to be ambitious' },
    ],
    correctAnswer: 'B',
    explanation: 'Stalled strategic plans are a signal, not a failure. The corrective action is focus (fewer priorities) and structure (weekly actions that feed into the task board, accountability check-ins).',
  },
  {
    id: 'M30-Q04',
    moduleId: 'M30',
    questionText: 'The meeting efficiency tool generates action items from a leadership meeting. Where do those action items go?',
    choices: [
      { label: 'A', text: 'They stay in the meeting notes' },
      { label: 'B', text: 'They auto-feed into the task board with assigned owners and deadlines' },
      { label: 'C', text: 'They get emailed to all families' },
      { label: 'D', text: 'They are deleted after the meeting' },
    ],
    correctAnswer: 'B',
    explanation: 'The connection between meeting decisions and task execution is the point. Action items that stay in meeting notes have a near-zero completion rate. Action items with owners and deadlines in the task system get done.',
  },
  {
    id: 'M30-Q05',
    moduleId: 'M30',
    questionText: 'An owner manages two sites and spends 15 hours per week driving between them. The cross-site dashboard reduces this to 5 hours. What should the owner do with the recovered 10 hours?',
    choices: [
      { label: 'A', text: 'Take more time off' },
      { label: 'B', text: 'Invest recovered time in strategic work: enrollment pipeline, financial planning, staff development, and community partnerships that grow the business' },
      { label: 'C', text: 'Micromanage both sites remotely' },
      { label: 'D', text: 'Open a third site immediately' },
    ],
    correctAnswer: 'B',
    explanation: 'Recovered operational time should shift to strategic time. The most common constraint for child care owners is being consumed by daily operations with no time for business growth.',
  },
];

export function getQuestionsForModule(moduleId: string): KnowledgeQuestion[] {
  return trainingQuestions.filter(q => q.moduleId === moduleId);
}

export function getModulesWithQuestions(): string[] {
  return Array.from(new Set(trainingQuestions.map(q => q.moduleId)));
}
